import Foundation

// MARK: - English Teaching Pack: German (Topics 1-18)

let deTeachingTopicsA: [(id: Int, title: String, intro: String, example: String)] = [
    (1, "Das Englische Alphabet", "Lerne die 26 Buchstaben des englischen Alphabets und ihre Aussprache. Das Alphabet besteht aus Vokalen (a, e, i, o, u) und Konsonanten.", "Der Buchstabe 'A' klingt wie in 'apple' (Apfel). Der Buchstabe 'B' klingt wie in 'ball' (Ball)."),
    (2, "Kurze Vokale", "Kurze Vokale erscheinen in einfachen Wörtern mit dem Muster Konsonant-Vokal-Konsonant (KVK). Lerne die fünf kurzen Vokale: a, e, i, o, u.", "Das Wort 'cat' (Katze) hat den kurzen Vokal 'a'. 'Dog' (Hund) hat den kurzen Vokal 'o'."),
    (3, "Häufige Wörter", "Häufige englische Wörter (Sight Words) kommen sehr oft in Texten vor und sollte man auswendig kennen.", "Die Wörter 'the', 'and', 'is', 'was', 'are' gehören zu den häufigsten englischen Wörtern."),
    (4, "Einfache Sätze", "Ein einfacher englischer Satz besteht aus Subjekt + Verb + Objekt. Das Verb steht immer nach dem Subjekt.", "Beispiel: 'The cat (Subjekt) eats (Verb) fish (Objekt).' = Die Katze isst Fisch."),
    (5, "Reime und Wortfamilien", "Englische Reimwörter enden mit dem gleichen Laut. Wortfamilien teilen dasselbe Endmuster.", "Die Wortfamilie '-at': cat, bat, hat, mat, rat. Alle reimen miteinander!"),
    (6, "Lange Vokale", "Lange Vokale klingen wie ihr Buchstabenname. Die stumme E-Regel: Ein 'e' am Wortende macht den Vokal davor lang.", "Das Wort 'cake' hat einen langen 'a'-Laut. Das stumme 'e' am Ende macht 'a' lang."),
    (7, "Konsonantenverbindungen", "Konsonantenverbindungen (Blends) sind zwei oder mehr Konsonanten zusammen. Digraphen sind zwei Buchstaben, die einen neuen Laut ergeben.", "Blend: 'bl' in 'blue', 'tr' in 'tree'. Digraph: 'sh' in 'ship', 'ch' in 'chair'."),
    (8, "Nomen und Verben", "Nomen (Nouns) sind Personen, Orte oder Dinge. Verben (Verbs) beschreiben Handlungen oder Zustände.", "Nomen: 'dog' (Hund), 'school' (Schule). Verb: 'run' (laufen), 'eat' (essen)."),
    (9, "Adjektive und Adverbien", "Adjektive beschreiben Nomen. Adverbien beschreiben Verben und sagen uns wie, wann oder wo etwas passiert.", "Adjektiv: 'big dog' (großer Hund). Adverb: 'runs quickly' (läuft schnell)."),
    (10, "Englische Zeichensetzung", "Satzzeichen helfen beim Lesen und Verstehen von Texten. Jeder englische Satz endet mit einem Satzzeichen.", "Punkt (.) für Aussagen. Fragezeichen (?) für Fragen. Ausrufezeichen (!) für Ausrufe."),
    (11, "Zusammengesetzte Wörter", "Zusammengesetzte Wörter (Compound Words) bestehen aus zwei oder mehr Wörtern. Kontraktionen verkürzen zwei Wörter mit einem Apostroph.", "Compound: 'sun' + 'shine' = 'sunshine'. Kontraktion: 'do not' = 'don't'."),
    (12, "Vor- und Nachsilben", "Vorsilben (Prefixes) kommen vor dem Wortstamm. Nachsilben (Suffixes) kommen nach dem Wortstamm und verändern die Bedeutung.", "Vorsilbe: 'un-' + 'happy' = 'unhappy' (unglücklich). Nachsilbe: 'play' + '-ing' = 'playing'."),
    (13, "Synonyme und Antonyme", "Synonyme sind Wörter mit ähnlicher Bedeutung. Antonyme sind Wörter mit entgegengesetzter Bedeutung.", "Synonym: 'happy' und 'glad' bedeuten beide glücklich. Antonym: 'big' und 'small' sind Gegensätze."),
    (14, "Leseverständnis", "Beim Leseverständnis findest du die Hauptidee eines Textes und beantwortest Fragen zu Wer, Was, Wo, Wann und Warum.", "Die Hauptidee ist das wichtigste Thema des Textes. Detailfragen helfen dir, den Text besser zu verstehen."),
    (15, "Geschichtselemente", "Jede Geschichte hat wichtige Elemente: Figuren (Characters), Handlungsort (Setting), Handlung (Plot), Problem und Lösung.", "Figur: der Held der Geschichte. Setting: Wo und wann die Geschichte spielt. Plot: Was passiert."),
    (16, "Satzarten", "Im Englischen gibt es vier Satzarten: Aussagesatz, Fragesatz, Ausrufesatz und Aufforderungssatz.", "Aussage: 'I like cats.' Frage: 'Do you like cats?' Ausruf: 'What a cute cat!' Aufforderung: 'Feed the cat!'"),
    (17, "Englische Homonyme", "Homonyme sind Wörter, die gleich klingen, aber unterschiedlich geschrieben werden und verschiedene Bedeutungen haben.", "there/their/they're: 'There' = dort, 'their' = ihr/ihre, 'they're' = they are."),
    (18, "Wortarten", "Die englischen Wortarten sind: Nomen, Verb, Adjektiv, Adverb, Pronomen, Präposition und mehr.", "Pronomen: 'he', 'she', 'it', 'they'. Präposition: 'in', 'on', 'under', 'behind'.")
]

// MARK: - Practice Questions (10 per topic)

let deTeachingPracticeA: [Int: [MathExamQuestion]] = [
    1: [
        MathExamQuestion(id: "de_teach_1_p1", topicId: 1, prompt: "Wie viele Buchstaben hat das englische Alphabet?", options: ["24", "25", "26", "27"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_p2", topicId: 1, prompt: "Welche dieser Gruppen enthält nur Vokale des englischen Alphabets?", options: ["a, b, c, d", "a, e, i, o, u", "a, e, i, o, y", "e, i, o, u, w"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_p3", topicId: 1, prompt: "Welcher Buchstabe kommt im englischen Alphabet nach 'M'?", options: ["L", "N", "O", "K"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_p4", topicId: 1, prompt: "Wie viele Vokale gibt es im englischen Alphabet?", options: ["3", "4", "5", "6"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_p5", topicId: 1, prompt: "Welcher Buchstabe ist der letzte im englischen Alphabet?", options: ["X", "Y", "Z", "W"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_p6", topicId: 1, prompt: "Wie viele Konsonanten hat das englische Alphabet?", options: ["19", "20", "21", "22"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_p7", topicId: 1, prompt: "Welcher Buchstabe steht an erster Stelle im englischen Alphabet?", options: ["E", "A", "I", "O"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_p8", topicId: 1, prompt: "Welcher dieser Buchstaben ist ein Konsonant?", options: ["A", "E", "I", "B"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_1_p9", topicId: 1, prompt: "Welcher Buchstabe kommt vor 'G' im englischen Alphabet?", options: ["H", "F", "E", "I"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_p10", topicId: 1, prompt: "In welcher Reihenfolge kommen diese Buchstaben im Alphabet? D, A, C, B", options: ["A, B, C, D", "B, A, D, C", "D, C, B, A", "A, C, B, D"], correctIndex: 0)
    ],
    2: [
        MathExamQuestion(id: "de_teach_2_p1", topicId: 2, prompt: "Welches Wort hat einen kurzen 'a'-Laut?", options: ["cake", "cat", "care", "came"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_2_p2", topicId: 2, prompt: "Welches Wort hat einen kurzen 'i'-Laut?", options: ["bike", "kite", "sit", "pine"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p3", topicId: 2, prompt: "Welches Wort hat einen kurzen 'o'-Laut?", options: ["hope", "bone", "dog", "home"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p4", topicId: 2, prompt: "Welches Wort hat einen kurzen 'u'-Laut?", options: ["cute", "mule", "cup", "tune"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p5", topicId: 2, prompt: "Welches Wort hat einen kurzen 'e'-Laut?", options: ["tree", "bee", "bed", "feet"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p6", topicId: 2, prompt: "Was bedeutet das englische Wort 'cat'?", options: ["Hund", "Vogel", "Katze", "Fisch"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p7", topicId: 2, prompt: "Welches dieser Wörter folgt dem KVK-Muster (Konsonant-Vokal-Konsonant)?", options: ["rain", "train", "hop", "sheep"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p8", topicId: 2, prompt: "Was bedeutet das englische Wort 'pen'?", options: ["Pfanne", "Stift", "Tier", "Buch"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_2_p9", topicId: 2, prompt: "Welches Wort hat denselben kurzen Vokal wie 'hat'?", options: ["hate", "hit", "bat", "hot"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_p10", topicId: 2, prompt: "Was bedeutet das englische Wort 'big'?", options: ["klein", "groß", "schnell", "langsam"], correctIndex: 1)
    ],
    3: [
        MathExamQuestion(id: "de_teach_3_p1", topicId: 3, prompt: "Was bedeutet das englische Wort 'the'?", options: ["ein/eine", "der/die/das", "und", "ist"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_p2", topicId: 3, prompt: "Was bedeutet das englische Wort 'and'?", options: ["oder", "aber", "und", "weil"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_p3", topicId: 3, prompt: "Was bedeutet das englische Wort 'said'?", options: ["sah", "sagte", "sang", "saß"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_p4", topicId: 3, prompt: "Was bedeutet das englische Wort 'they'?", options: ["er", "sie (Einzahl)", "sie (Mehrzahl)", "wir"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_p5", topicId: 3, prompt: "Was bedeutet das englische Wort 'have'?", options: ["sein", "haben", "machen", "gehen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_p6", topicId: 3, prompt: "Welches Wort bedeutet 'von' auf Englisch?", options: ["for", "from", "with", "at"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_p7", topicId: 3, prompt: "Was bedeutet 'are' auf Deutsch?", options: ["ist", "war", "sind/bist", "hat"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_p8", topicId: 3, prompt: "Welches dieser Wörter bedeutet 'du/ihr' auf Englisch?", options: ["we", "you", "they", "I"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_p9", topicId: 3, prompt: "Was bedeutet 'was' auf Englisch (Vergangenheit von 'is')?", options: ["is", "are", "was", "were"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_p10", topicId: 3, prompt: "Welches Wort bedeutet 'wir' auf Englisch?", options: ["I", "you", "we", "they"], correctIndex: 2)
    ],
    4: [
        MathExamQuestion(id: "de_teach_4_p1", topicId: 4, prompt: "Was ist das Subjekt im Satz 'The dog runs fast'?", options: ["runs", "fast", "The dog", "dog runs"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_p2", topicId: 4, prompt: "Was ist das Verb im Satz 'She eats an apple'?", options: ["She", "eats", "an", "apple"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_4_p3", topicId: 4, prompt: "Welcher Satz ist grammatikalisch korrekt?", options: ["Runs the cat fast.", "The cat runs fast.", "Fast runs the cat.", "The fast cat runs."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_4_p4", topicId: 4, prompt: "Was ist das Objekt im Satz 'Tom kicks the ball'?", options: ["Tom", "kicks", "the", "the ball"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_4_p5", topicId: 4, prompt: "Wie lautet die korrekte Wortstellung im Englischen?", options: ["Verb + Subjekt + Objekt", "Objekt + Verb + Subjekt", "Subjekt + Verb + Objekt", "Subjekt + Objekt + Verb"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_p6", topicId: 4, prompt: "Welcher Satz bedeutet 'Ich mag Bücher'?", options: ["Books like I.", "I books like.", "Like I books.", "I like books."], correctIndex: 3),
        MathExamQuestion(id: "de_teach_4_p7", topicId: 4, prompt: "Was bedeutet 'She plays football' auf Deutsch?", options: ["Er spielt Fußball.", "Sie spielt Fußball.", "Wir spielen Fußball.", "Sie spielen Fußball."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_4_p8", topicId: 4, prompt: "Welches Wort fehlt? 'The bird ___ in the tree.'", options: ["runs", "swims", "sits", "eats"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_p9", topicId: 4, prompt: "Was bedeutet 'We read books every day'?", options: ["Wir lesen täglich Bücher.", "Sie lesen täglich Bücher.", "Ich lese täglich Bücher.", "Er liest täglich Bücher."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_4_p10", topicId: 4, prompt: "Welcher Teil des Satzes sagt uns, was die Person tut?", options: ["Subjekt", "Objekt", "Artikel", "Verb"], correctIndex: 3)
    ],
    5: [
        MathExamQuestion(id: "de_teach_5_p1", topicId: 5, prompt: "Welches Wort reimt mit 'cat'?", options: ["car", "bat", "cut", "coat"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_5_p2", topicId: 5, prompt: "Welches Wort reimt mit 'can'?", options: ["con", "coin", "man", "moon"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_p3", topicId: 5, prompt: "Welche Wörter gehören zur Wortfamilie '-at'?", options: ["bat, hat, mat", "bit, hit, sit", "but, cut, hut", "bet, get, net"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_5_p4", topicId: 5, prompt: "Welches Wort reimt NICHT mit den anderen?", options: ["dog", "log", "fog", "bag"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_5_p5", topicId: 5, prompt: "Welche Wörter gehören zur Wortfamilie '-an'?", options: ["can, man, ran", "bin, fin, tin", "fun, run, sun", "hen, men, ten"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_5_p6", topicId: 5, prompt: "Welches Wort reimt mit 'hop'?", options: ["hip", "hap", "top", "tip"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_p7", topicId: 5, prompt: "Was haben Reimwörter gemeinsam?", options: ["Denselben Anfangsbuchstaben", "Dieselbe Bedeutung", "Denselben Endlaut", "Dieselbe Länge"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_p8", topicId: 5, prompt: "Welches Wort reimt mit 'run'?", options: ["ran", "rain", "sun", "sin"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_p9", topicId: 5, prompt: "Zur welchen Wortfamilie gehört 'big'?", options: ["-ig", "-it", "-in", "-id"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_5_p10", topicId: 5, prompt: "Welches Wort gehört NICHT zur Wortfamilie '-it'?", options: ["bit", "hit", "sit", "set"], correctIndex: 3)
    ],
    6: [
        MathExamQuestion(id: "de_teach_6_p1", topicId: 6, prompt: "Welches Wort hat einen langen 'a'-Laut?", options: ["cat", "cake", "cap", "can"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_p2", topicId: 6, prompt: "Was bewirkt das stumme 'e' am Ende eines Wortes?", options: ["Es macht den Vokal kurz.", "Es macht den Vokal lang.", "Es fügt eine Silbe hinzu.", "Es ändert den Konsonanten."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_p3", topicId: 6, prompt: "Welches Wort hat einen langen 'i'-Laut?", options: ["sit", "bit", "bike", "kick"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_p4", topicId: 6, prompt: "Welches Wort hat einen langen 'o'-Laut?", options: ["hop", "hot", "pot", "hope"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_6_p5", topicId: 6, prompt: "Welches Wort hat einen langen 'u'-Laut?", options: ["cup", "cut", "cute", "cub"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_p6", topicId: 6, prompt: "Was passiert, wenn man 'cap' zu 'cape' ändert?", options: ["Der 'a'-Laut wird kurz.", "Der 'a'-Laut wird lang.", "Das Wort bedeutet dasselbe.", "Der Konsonant ändert sich."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_p7", topicId: 6, prompt: "Welches Wort hat einen langen 'e'-Laut?", options: ["bed", "red", "pet", "tree"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_6_p8", topicId: 6, prompt: "Was bedeutet 'bike' auf Deutsch?", options: ["Buch", "Fahrrad", "Vogel", "Bett"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_p9", topicId: 6, prompt: "Welches Wort folgt der stummen E-Regel?", options: ["kick", "stick", "kite", "kit"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_p10", topicId: 6, prompt: "Welches Wort hat KEINEN langen Vokal?", options: ["cake", "bike", "hope", "hop"], correctIndex: 3)
    ],
    7: [
        MathExamQuestion(id: "de_teach_7_p1", topicId: 7, prompt: "Was ist ein 'Blend' (Konsonantenverbindung) im Englischen?", options: ["Ein einzelner Konsonant", "Zwei Vokale zusammen", "Zwei oder mehr Konsonanten, die man einzeln hört", "Zwei Buchstaben mit einem neuen Laut"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_p2", topicId: 7, prompt: "Welches Wort beginnt mit dem Digraphen 'sh'?", options: ["star", "ship", "spin", "sleep"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_p3", topicId: 7, prompt: "Welches Wort beginnt mit dem Blend 'bl'?", options: ["bright", "blue", "chin", "this"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_p4", topicId: 7, prompt: "Was ist ein Digraph?", options: ["Ein langer Vokal", "Zwei Konsonanten mit eigenem Laut", "Eine Wortfamilie", "Ein kurzer Vokal"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_p5", topicId: 7, prompt: "Welches Wort beginnt mit dem Digraphen 'ch'?", options: ["this", "phone", "chair", "star"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_p6", topicId: 7, prompt: "Welcher Blend steckt am Anfang von 'tree'?", options: ["tr", "br", "cr", "dr"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_7_p7", topicId: 7, prompt: "Welches Wort enthält den Digraphen 'th'?", options: ["ship", "chip", "this", "whip"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_p8", topicId: 7, prompt: "Welches Wort beginnt mit dem Blend 'st'?", options: ["ship", "chin", "star", "thin"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_p9", topicId: 7, prompt: "Welches Wort beginnt mit dem Digraphen 'wh'?", options: ["where", "there", "here", "share"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_7_p10", topicId: 7, prompt: "Welcher Blend steckt am Anfang von 'spider'?", options: ["sl", "sp", "st", "sw"], correctIndex: 1)
    ],
    8: [
        MathExamQuestion(id: "de_teach_8_p1", topicId: 8, prompt: "Was ist ein Nomen (Noun) im Englischen?", options: ["Eine Handlung", "Eine Person, ein Ort oder ein Ding", "Ein Beschreibungswort", "Ein Verbindungswort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_p2", topicId: 8, prompt: "Welches dieser Wörter ist ein Nomen?", options: ["run", "happy", "school", "quickly"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_p3", topicId: 8, prompt: "Was ist ein Verb im Englischen?", options: ["Ein Ding", "Ein Ort", "Eine Handlung oder ein Zustand", "Eine Eigenschaft"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_p4", topicId: 8, prompt: "Welches dieser Wörter ist ein Verb?", options: ["cat", "jump", "blue", "house"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_p5", topicId: 8, prompt: "Wie lautet der korrekte Plural von 'cat'?", options: ["cates", "cats", "cat's", "catis"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_p6", topicId: 8, prompt: "Wie lautet der korrekte Plural von 'child'?", options: ["childs", "childes", "children", "child's"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_p7", topicId: 8, prompt: "Welches Wort ist sowohl ein Nomen als auch ein Verb?", options: ["happy", "run", "big", "slowly"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_p8", topicId: 8, prompt: "Was bedeutet 'to swim' auf Deutsch?", options: ["singen", "springen", "schwimmen", "laufen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_p9", topicId: 8, prompt: "Welches Wort ist ein Nomen?", options: ["eat", "sleep", "teacher", "write"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_p10", topicId: 8, prompt: "Wie lautet der Plural von 'box'?", options: ["boxs", "boxen", "boxes", "box"], correctIndex: 2)
    ],
    9: [
        MathExamQuestion(id: "de_teach_9_p1", topicId: 9, prompt: "Was beschreibt ein Adjektiv im Englischen?", options: ["Eine Handlung", "Ein Nomen", "Ein Verb", "Einen Ort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_p2", topicId: 9, prompt: "Welches dieser Wörter ist ein Adjektiv?", options: ["run", "quickly", "beautiful", "sing"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_p3", topicId: 9, prompt: "Was beschreibt ein Adverb hauptsächlich?", options: ["Ein Nomen", "Einen Ort", "Ein Verb", "Ein Adjektiv"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_p4", topicId: 9, prompt: "Welches dieser Wörter ist ein Adverb?", options: ["big", "small", "quickly", "red"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_p5", topicId: 9, prompt: "Welches Adjektiv ist das Gegenteil von 'big'?", options: ["large", "huge", "small", "tall"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_p6", topicId: 9, prompt: "Wie nennt man die Steigerungsform von Adjektiven? Z.B. big → bigger → ___", options: ["biggest", "bigly", "most big", "bigest"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_9_p7", topicId: 9, prompt: "Was bedeutet 'slowly' auf Deutsch?", options: ["schnell", "langsam", "laut", "leise"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_p8", topicId: 9, prompt: "Welches Adverb passt in den Satz: 'She speaks ___.'?", options: ["loud", "loudly", "louder", "loudest"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_p9", topicId: 9, prompt: "Welches Adjektiv passt? 'The ___ dog barks all night.'", options: ["runs", "quickly", "loud", "slowly"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_p10", topicId: 9, prompt: "Was bedeutet 'fast' als Adjektiv auf Deutsch?", options: ["langsam", "groß", "schnell", "laut"], correctIndex: 2)
    ],
    10: [
        MathExamQuestion(id: "de_teach_10_p1", topicId: 10, prompt: "Welches Satzzeichen steht am Ende einer Aussage?", options: ["?", "!", ".", ","], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_p2", topicId: 10, prompt: "Welches Satzzeichen steht am Ende einer Frage?", options: [".", "!", "?", ","], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_p3", topicId: 10, prompt: "Welches Satzzeichen benutzt man bei einem Ausruf?", options: [".", "?", ",", "!"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_10_p4", topicId: 10, prompt: "Wofür benutzt man ein Komma im Englischen?", options: ["Am Ende eines Satzes", "Um eine Liste aufzuzählen", "Am Anfang eines Satzes", "Für Fragen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_p5", topicId: 10, prompt: "Welches Satzzeichen fehlt? 'What time is it___'", options: [".", ",", "!", "?"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_10_p6", topicId: 10, prompt: "Welches Satzzeichen fehlt? 'I love my dog___'", options: ["?", "!", ",", "All of the above"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_p7", topicId: 10, prompt: "Wann schreibt man im Englischen einen Großbuchstaben?", options: ["Nur am Satzende", "Am Satzanfang und bei Namen", "Nur bei Nomen", "Immer bei Verben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_p8", topicId: 10, prompt: "Was ist ein Apostroph (') im Englischen?", options: ["Ein Ausrufezeichen", "Ein Anführungszeichen", "Ein Zeichen für Auslassung oder Besitz", "Ein Komma"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_p9", topicId: 10, prompt: "Welcher Satz ist korrekt interpunktiert?", options: ["I like dogs? cats and birds.", "I like dogs cats and birds.", "I like dogs, cats, and birds.", "i like dogs, cats, and birds"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_p10", topicId: 10, prompt: "Welches Satzzeichen trennt Einträge in einer Liste?", options: ["Punkt", "Ausrufezeichen", "Komma", "Fragezeichen"], correctIndex: 2)
    ],
    11: [
        MathExamQuestion(id: "de_teach_11_p1", topicId: 11, prompt: "Was ist ein zusammengesetztes Wort (Compound Word)?", options: ["Ein Wort mit einer Vorsilbe", "Zwei Wörter zu einem neuen Wort", "Ein Wort mit einer Nachsilbe", "Ein verkürztes Wort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_11_p2", topicId: 11, prompt: "Welche zwei Wörter bilden 'sunshine'?", options: ["sun + ship", "sun + shine", "sun + line", "sum + shine"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_11_p3", topicId: 11, prompt: "Was ist eine Kontraktion im Englischen?", options: ["Ein zusammengesetztes Wort", "Zwei Wörter mit Apostroph verkürzt", "Ein Nomen im Plural", "Ein langer Vokal"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_11_p4", topicId: 11, prompt: "Was ist die Langform von 'don't'?", options: ["does not", "did not", "do not", "done not"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_11_p5", topicId: 11, prompt: "Was ist die Langform von \"I'm\"?", options: ["I am", "I have", "I will", "I was"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_p6", topicId: 11, prompt: "Welche zwei Wörter bilden 'football'?", options: ["foot + ball", "fool + tall", "food + ball", "foot + fall"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_p7", topicId: 11, prompt: "Was ist die Kurzform von 'cannot'?", options: ["can't", "cant", "ca'not", "can'nt"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_p8", topicId: 11, prompt: "Welches ist ein zusammengesetztes Wort?", options: ["running", "unhappy", "rainbow", "quickly"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_11_p9", topicId: 11, prompt: "Was ist die Langform von \"they're\"?", options: ["they are", "their", "there", "they were"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_p10", topicId: 11, prompt: "Welche zwei Wörter bilden 'birthday'?", options: ["bird + day", "birth + day", "big + day", "bit + today"], correctIndex: 1)
    ],
    12: [
        MathExamQuestion(id: "de_teach_12_p1", topicId: 12, prompt: "Was ist eine Vorsilbe (Prefix)?", options: ["Silbe nach dem Wortstamm", "Silbe vor dem Wortstamm", "Das Ende eines Satzes", "Ein zusammengesetztes Wort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p2", topicId: 12, prompt: "Was bedeutet die Vorsilbe 'un-' im Englischen?", options: ["wieder", "nicht/das Gegenteil", "mehr als", "sehr"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p3", topicId: 12, prompt: "Was bedeutet 'unhappy'?", options: ["sehr glücklich", "nicht glücklich", "wieder glücklich", "ziemlich glücklich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p4", topicId: 12, prompt: "Was bedeutet die Vorsilbe 're-' im Englischen?", options: ["nicht", "wieder", "vor", "nach"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p5", topicId: 12, prompt: "Was bedeutet 'rewrite'?", options: ["falsch schreiben", "wieder schreiben", "nicht schreiben", "schnell schreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p6", topicId: 12, prompt: "Was wird aus 'play' mit der Nachsilbe '-ing'?", options: ["played", "plays", "playing", "player"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_p7", topicId: 12, prompt: "Was bedeutet die Nachsilbe '-ful'?", options: ["ohne", "voll von", "wieder", "nicht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p8", topicId: 12, prompt: "Was bedeutet 'hopeless'?", options: ["hoffnungsvoll", "sehr hoffnungsvoll", "ohne Hoffnung", "mit Hoffnung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_p9", topicId: 12, prompt: "Was ist die Komparativform von 'tall' mit '-er'?", options: ["tallest", "taller", "talling", "talled"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_p10", topicId: 12, prompt: "Welches Wort hat eine Vorsilbe?", options: ["playing", "teacher", "redo", "quickly"], correctIndex: 2)
    ],
    13: [
        MathExamQuestion(id: "de_teach_13_p1", topicId: 13, prompt: "Was sind Synonyme?", options: ["Wörter mit entgegengesetzter Bedeutung", "Wörter mit ähnlicher Bedeutung", "Wörter die gleich klingen", "Zusammengesetzte Wörter"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_13_p2", topicId: 13, prompt: "Was sind Antonyme?", options: ["Wörter mit ähnlicher Bedeutung", "Wörter die gleich klingen", "Wörter mit entgegengesetzter Bedeutung", "Reime"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_p3", topicId: 13, prompt: "Was ist ein Synonym für 'happy'?", options: ["sad", "glad", "angry", "tired"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_13_p4", topicId: 13, prompt: "Was ist das Antonym von 'big'?", options: ["large", "huge", "small", "tall"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_p5", topicId: 13, prompt: "Was ist ein Synonym für 'fast'?", options: ["slow", "quick", "quiet", "soft"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_13_p6", topicId: 13, prompt: "Was ist das Antonym von 'hot'?", options: ["warm", "cool", "cold", "mild"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_p7", topicId: 13, prompt: "Was ist ein Synonym für 'begin'?", options: ["end", "finish", "stop", "start"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_13_p8", topicId: 13, prompt: "Was ist das Antonym von 'day'?", options: ["noon", "morning", "night", "evening"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_p9", topicId: 13, prompt: "Welches Wort ist ein Synonym für 'angry'?", options: ["happy", "sad", "mad", "glad"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_p10", topicId: 13, prompt: "Was ist das Antonym von 'open'?", options: ["wide", "ajar", "close", "closed"], correctIndex: 3)
    ],
    14: [
        MathExamQuestion(id: "de_teach_14_p1", topicId: 14, prompt: "Was ist die 'Hauptidee' (main idea) eines Textes?", options: ["Ein unwichtiges Detail", "Das wichtigste Thema des Textes", "Der erste Satz", "Der letzte Satz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_p2", topicId: 14, prompt: "Was fragt die 'Wer'-Frage (who) in einem Text?", options: ["Nach dem Ort", "Nach der Zeit", "Nach der Person oder dem Tier", "Nach dem Grund"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_p3", topicId: 14, prompt: "Was fragt die 'Wo'-Frage (where) in einem Text?", options: ["Nach dem Ort", "Nach der Person", "Nach der Zeit", "Nach dem Grund"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_14_p4", topicId: 14, prompt: "Was fragt die 'Warum'-Frage (why) in einem Text?", options: ["Nach dem Ort", "Nach der Person", "Nach dem Grund oder der Ursache", "Nach der Zeit"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_p5", topicId: 14, prompt: "Was sind 'Details' in einem Text?", options: ["Die Hauptidee", "Zusätzliche Informationen zur Hauptidee", "Der Titel", "Die Moral"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_p6", topicId: 14, prompt: "Was fragt die 'Wann'-Frage (when) in einem Text?", options: ["Nach der Person", "Nach dem Ort", "Nach der Zeit oder dem Datum", "Nach dem Grund"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_p7", topicId: 14, prompt: "Was fragt die 'Was'-Frage (what) in einem Text?", options: ["Nach der Person", "Nach der Sache oder dem Ereignis", "Nach dem Ort", "Nach dem Grund"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_p8", topicId: 14, prompt: "Wie findet man die Hauptidee eines Textes?", options: ["Nur den ersten Satz lesen", "Nur den letzten Satz lesen", "Den ganzen Text lesen und das wichtigste Thema finden", "Den Titel ignorieren"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_p9", topicId: 14, prompt: "Was ist ein 'Schluss' (conclusion) bei einem Text?", options: ["Die Einleitung", "Das Ende oder die Zusammenfassung", "Die Hauptidee", "Ein Detail"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_p10", topicId: 14, prompt: "Was helfen Fragen wie 'Who? What? Where? When? Why?' beim Lesen?", options: ["Den Text zu ignorieren", "Das Leseverständnis zu verbessern", "Nur Wörter zu buchstabieren", "Reime zu finden"], correctIndex: 1)
    ],
    15: [
        MathExamQuestion(id: "de_teach_15_p1", topicId: 15, prompt: "Was sind 'Figuren' (characters) in einer Geschichte?", options: ["Der Ort der Handlung", "Was in der Geschichte passiert", "Die Personen oder Tiere in der Geschichte", "Die Moral der Geschichte"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_p2", topicId: 15, prompt: "Was ist das 'Setting' einer Geschichte?", options: ["Die Figuren", "Die Handlung", "Wo und wann die Geschichte spielt", "Das Problem"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_p3", topicId: 15, prompt: "Was ist der 'Plot' einer Geschichte?", options: ["Der Ort", "Was in der Geschichte passiert", "Die Figuren", "Die Lösung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_p4", topicId: 15, prompt: "Was ist das 'Problem' in einer Geschichte?", options: ["Die Lösung", "Die Hauptfigur", "Die Schwierigkeit, die die Figuren überwinden müssen", "Das Ende"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_p5", topicId: 15, prompt: "Was ist die 'Lösung' (solution) in einer Geschichte?", options: ["Das Problem", "Wie das Problem gelöst wird", "Der Anfang der Geschichte", "Das Setting"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_p6", topicId: 15, prompt: "Was ist die 'Hauptfigur' (main character)?", options: ["Eine unwichtige Person in der Geschichte", "Die wichtigste Person oder das wichtigste Tier", "Der Ort der Handlung", "Das Ende der Geschichte"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_p7", topicId: 15, prompt: "Was passiert am Anfang (beginning) einer Geschichte?", options: ["Das Problem wird gelöst", "Die Figuren und das Setting werden vorgestellt", "Die Geschichte endet", "Die Moral wird genannt"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_p8", topicId: 15, prompt: "Was passiert am Ende (ending) einer Geschichte?", options: ["Neue Figuren werden eingeführt", "Das Setting wird beschrieben", "Das Problem wird normalerweise gelöst", "Die Geschichte beginnt neu"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_p9", topicId: 15, prompt: "Was ist die 'Moral' einer Geschichte?", options: ["Der Ort der Geschichte", "Die wichtigste Figur", "Die Lektion, die man aus der Geschichte lernt", "Das Problem der Geschichte"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_p10", topicId: 15, prompt: "Welche fünf Elemente gehören zu einer vollständigen Geschichte?", options: ["Titel, Autor, Bilder, Seiten, Wörter", "Figuren, Setting, Plot, Problem, Lösung", "Anfang, Mitte, Ende, Moral, Figuren", "Fragen, Antworten, Details, Ideen, Fakten"], correctIndex: 1)
    ],
    16: [
        MathExamQuestion(id: "de_teach_16_p1", topicId: 16, prompt: "Was ist ein Aussagesatz (declarative sentence)?", options: ["Eine Frage", "Ein Ausruf", "Eine Aussage oder Feststellung", "Eine Aufforderung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p2", topicId: 16, prompt: "Was ist ein Fragesatz (interrogative sentence)?", options: ["Ein Satz der etwas ausruft", "Ein Satz der fragt", "Ein Satz der auffordert", "Ein Satz der behauptet"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_16_p3", topicId: 16, prompt: "Was ist ein Ausrufesatz (exclamatory sentence)?", options: ["Ein Fragesatz", "Ein Aussagesatz", "Ein Satz mit starker Emotion", "Ein Aufforderungssatz"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p4", topicId: 16, prompt: "Was ist ein Aufforderungssatz (imperative sentence)?", options: ["Ein Satz der fragt", "Ein Satz der eine Emotion ausdrückt", "Ein Satz der befiehlt oder bittet", "Ein Satz der behauptet"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p5", topicId: 16, prompt: "Welcher Satz ist ein Fragesatz?", options: ["I like pizza.", "Do you like pizza?", "I love pizza!", "Eat your pizza."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_16_p6", topicId: 16, prompt: "Welcher Satz ist ein Ausrufesatz?", options: ["Where is my bag?", "Please sit down.", "What a beautiful day!", "I go to school."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p7", topicId: 16, prompt: "Welcher Satz ist ein Aufforderungssatz?", options: ["The sun is bright.", "Is the sun bright?", "What a bright sun!", "Look at the bright sun."], correctIndex: 3),
        MathExamQuestion(id: "de_teach_16_p8", topicId: 16, prompt: "Mit welchem Satzzeichen endet ein Aussagesatz?", options: ["!", "?", ".", ","], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p9", topicId: 16, prompt: "Welcher Satz ist ein Aussagesatz?", options: ["Run fast!", "Do you run fast?", "The dog runs fast.", "Run, dog!"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_p10", topicId: 16, prompt: "Welche vier Satzarten gibt es im Englischen?", options: ["Lang, kurz, mittel, sehr kurz", "Aussage, Frage, Ausruf, Aufforderung", "Nomen, Verb, Adjektiv, Adverb", "Anfang, Mitte, Ende, Schluss"], correctIndex: 1)
    ],
    17: [
        MathExamQuestion(id: "de_teach_17_p1", topicId: 17, prompt: "Was bedeutet 'there' im Englischen?", options: ["ihr/ihre (Besitz)", "they are (Kurzform)", "dort/da", "das Pronomen 'sie'"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p2", topicId: 17, prompt: "Was bedeutet 'their' im Englischen?", options: ["dort/da", "they are", "ihr/ihre (Besitz)", "dort drüben"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p3", topicId: 17, prompt: "Was ist die Langform von \"they're\"?", options: ["there", "their", "they are", "they were"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p4", topicId: 17, prompt: "Welches Wort passt? '___ going to the park today.' (Sie gehen heute in den Park.)", options: ["There", "Their", "They're", "Theyre"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p5", topicId: 17, prompt: "Was bedeutet 'to' im Satz 'I go to school'?", options: ["auch", "zwei", "zu/nach", "sehr"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p6", topicId: 17, prompt: "Was bedeutet 'too' im Englischen?", options: ["zu/nach", "zwei", "auch / zu sehr", "sehr klein"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_p7", topicId: 17, prompt: "Was bedeutet 'two' im Englischen?", options: ["zu/nach", "auch", "sehr", "zwei"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_17_p8", topicId: 17, prompt: "Welches Wort passt? 'Is this ___ book?' (Ist das dein Buch?)", options: ["you're", "your", "yore", "you are"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_17_p9", topicId: 17, prompt: "Was ist die Langform von \"you're\"?", options: ["your", "you are", "you were", "you have"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_17_p10", topicId: 17, prompt: "Welches Wort passt? 'The cat hurt ___ paw.' (Die Katze hat ihre Pfote verletzt.)", options: ["it's", "its", "its'", "it is"], correctIndex: 1)
    ],
    18: [
        MathExamQuestion(id: "de_teach_18_p1", topicId: 18, prompt: "Was ist ein Pronomen (pronoun)?", options: ["Ein Beschreibungswort", "Ein Wort das ein Nomen ersetzt", "Eine Handlung", "Ein Verbindungswort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_18_p2", topicId: 18, prompt: "Welches dieser Wörter ist ein Pronomen?", options: ["run", "happy", "she", "school"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_p3", topicId: 18, prompt: "Was ist eine Präposition (preposition)?", options: ["Ein Verb", "Ein Nomen", "Ein Wort das eine Beziehung zwischen Wörtern beschreibt", "Ein Adjektiv"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_p4", topicId: 18, prompt: "Welches dieser Wörter ist eine Präposition?", options: ["run", "happy", "quickly", "under"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_18_p5", topicId: 18, prompt: "Welche Wortart ist 'quickly' im Satz 'She runs quickly'?", options: ["Nomen", "Verb", "Adjektiv", "Adverb"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_18_p6", topicId: 18, prompt: "Welche Wortart ist 'beautiful' im Satz 'She has a beautiful dress'?", options: ["Nomen", "Verb", "Adjektiv", "Adverb"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_p7", topicId: 18, prompt: "Welche Wortart ist 'eats' im Satz 'The dog eats'?", options: ["Nomen", "Verb", "Adjektiv", "Pronomen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_18_p8", topicId: 18, prompt: "Welche Wortart ist 'dog' im Satz 'The dog runs'?", options: ["Verb", "Adjektiv", "Nomen", "Pronomen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_p9", topicId: 18, prompt: "Welche Wortart ist 'he' im Satz 'He plays football'?", options: ["Nomen", "Pronomen", "Verb", "Adjektiv"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_18_p10", topicId: 18, prompt: "Welche sechs Hauptwortarten gibt es im Englischen?", options: ["Nomen, Verb, Adjektiv, Adverb, Pronomen, Präposition", "Nomen, Verb, Adjektiv, Satz, Frage, Ausruf", "Groß, klein, mittel, kurz, lang, sehr lang", "Vokal, Konsonant, Blend, Digraph, Reim, Silbe"], correctIndex: 0)
    ]
]

// MARK: - Exam Questions (10 per topic)

let deTeachingExamA: [Int: [MathExamQuestion]] = [
    1: [
        MathExamQuestion(id: "de_teach_1_e1", topicId: 1, prompt: "In welcher Reihenfolge kommen diese Buchstaben im Alphabet? P, M, R, N", options: ["M, N, P, R", "P, M, N, R", "R, P, N, M", "N, M, P, R"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_1_e2", topicId: 1, prompt: "Welcher Buchstabe ist der zehnte im englischen Alphabet?", options: ["I", "J", "K", "H"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_e3", topicId: 1, prompt: "Welches dieser Wörter beginnt mit einem Vokal?", options: ["ball", "dog", "elephant", "fish"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_e4", topicId: 1, prompt: "Wie viele Buchstaben liegen zwischen 'C' und 'G' im Alphabet?", options: ["2", "3", "4", "5"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_e5", topicId: 1, prompt: "Welcher Buchstabe kommt direkt nach 'T' im Alphabet?", options: ["S", "R", "U", "V"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_e6", topicId: 1, prompt: "Welcher dieser Buchstaben ist der 13. im englischen Alphabet?", options: ["L", "M", "N", "K"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_e7", topicId: 1, prompt: "Welches Wort hat den ersten Buchstaben des Alphabets?", options: ["ball", "cake", "apple", "dog"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_e8", topicId: 1, prompt: "Welcher Buchstabe ist der vorletzte im englischen Alphabet?", options: ["X", "Y", "Z", "W"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_1_e9", topicId: 1, prompt: "Wie nennt man Buchstaben, die keine Vokale sind?", options: ["Digraphen", "Blends", "Konsonanten", "Silben"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_1_e10", topicId: 1, prompt: "Welches dieser Wörter beginnt mit dem fünften Buchstaben des Alphabets?", options: ["dog", "elephant", "fish", "cat"], correctIndex: 1)
    ],
    2: [
        MathExamQuestion(id: "de_teach_2_e1", topicId: 2, prompt: "Welches Wort hat denselben kurzen Vokal wie 'sit'?", options: ["kite", "bite", "hit", "site"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e2", topicId: 2, prompt: "Was bedeutet das englische Wort 'hot'?", options: ["kalt", "heiß", "warm", "kühl"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_2_e3", topicId: 2, prompt: "Welches Wort folgt dem KVK-Muster?", options: ["tree", "play", "mud", "rain"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e4", topicId: 2, prompt: "Welches Wort hat denselben kurzen Vokal wie 'cup'?", options: ["cube", "mule", "pup", "tube"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e5", topicId: 2, prompt: "Was bedeutet 'wet' auf Deutsch?", options: ["trocken", "nass", "kalt", "warm"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_2_e6", topicId: 2, prompt: "Welches Wort hat denselben kurzen Vokal wie 'log'?", options: ["hope", "bone", "home", "dot"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_2_e7", topicId: 2, prompt: "Was bedeutet das englische Wort 'red'?", options: ["blau", "grün", "rot", "gelb"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e8", topicId: 2, prompt: "Wie viele kurze Vokale gibt es im Englischen?", options: ["3", "4", "5", "6"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e9", topicId: 2, prompt: "Welches Wort hat denselben kurzen Vokal wie 'bed'?", options: ["tree", "bee", "ten", "feet"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_2_e10", topicId: 2, prompt: "Was bedeutet das englische Wort 'fun'?", options: ["lustig/Spaß", "Sonne", "laufen", "sitzen"], correctIndex: 0)
    ],
    3: [
        MathExamQuestion(id: "de_teach_3_e1", topicId: 3, prompt: "Was bedeutet 'from' auf Deutsch?", options: ["für", "von/aus", "mit", "zu"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_e2", topicId: 3, prompt: "Welches dieser Wörter bedeutet 'er' auf Englisch?", options: ["she", "they", "he", "we"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_e3", topicId: 3, prompt: "Was bedeutet 'with' auf Deutsch?", options: ["ohne", "mit", "für", "gegen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_e4", topicId: 3, prompt: "Was bedeutet 'what' auf Deutsch?", options: ["wer", "wann", "was", "wo"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_e5", topicId: 3, prompt: "Welches Wort bedeutet 'hier' auf Englisch?", options: ["there", "where", "here", "hear"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_e6", topicId: 3, prompt: "Was bedeutet 'when' auf Deutsch?", options: ["wo", "wer", "wie", "wann"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_3_e7", topicId: 3, prompt: "Was bedeutet 'some' auf Deutsch?", options: ["alle", "keine", "einige/etwas", "viele"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_e8", topicId: 3, prompt: "Welches Wort bedeutet 'er/sie/es hat' auf Englisch?", options: ["have", "had", "has", "having"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_3_e9", topicId: 3, prompt: "Was bedeutet 'this' auf Deutsch?", options: ["jenes/jener", "diese/dieser/dieses", "jene", "alle"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_3_e10", topicId: 3, prompt: "Welches Wort bedeutet 'nicht' auf Englisch?", options: ["now", "new", "not", "no"], correctIndex: 2)
    ],
    4: [
        MathExamQuestion(id: "de_teach_4_e1", topicId: 4, prompt: "Welcher Satz ist grammatikalisch korrekt?", options: ["Plays she tennis.", "She tennis plays.", "Tennis she plays.", "She plays tennis."], correctIndex: 3),
        MathExamQuestion(id: "de_teach_4_e2", topicId: 4, prompt: "Was ist das Subjekt im Satz 'My sister loves music'?", options: ["loves", "music", "My sister", "my"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_e3", topicId: 4, prompt: "Was bedeutet 'The children play in the park'?", options: ["Die Kinder spielen im Park.", "Das Kind spielt im Park.", "Die Kinder laufen im Park.", "Ein Kind spielt im Garten."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_4_e4", topicId: 4, prompt: "Welches Verb passt? 'Birds ___ in the sky.'", options: ["swim", "run", "fly", "hop"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_e5", topicId: 4, prompt: "Was ist das Verb im Satz 'The teacher reads a book'?", options: ["teacher", "reads", "book", "the"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_4_e6", topicId: 4, prompt: "Welcher Satz bedeutet 'Wir essen Pizza zum Abendessen'?", options: ["We eat pizza for dinner.", "They eat pizza for lunch.", "I eat pizza for dinner.", "We ate pizza for dinner."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_4_e7", topicId: 4, prompt: "Was ist das Objekt im Satz 'Lisa writes a letter'?", options: ["Lisa", "writes", "a letter", "a"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_4_e8", topicId: 4, prompt: "Welches Wort fehlt? 'He ___ to school every day.'", options: ["go", "goes", "gone", "going"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_4_e9", topicId: 4, prompt: "Was bedeutet 'They watch television in the evening'?", options: ["Sie sehen abends fern.", "Wir sehen abends fern.", "Er sieht abends fern.", "Sie sehen morgens fern."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_4_e10", topicId: 4, prompt: "Welcher Satz ist ein vollständiger englischer Satz?", options: ["Runs fast very.", "The fast boy.", "The boy runs fast.", "Boy fast runs."], correctIndex: 2)
    ],
    5: [
        MathExamQuestion(id: "de_teach_5_e1", topicId: 5, prompt: "Welches Wort reimt mit 'night'?", options: ["neat", "note", "light", "knot"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_e2", topicId: 5, prompt: "Welche Wörter gehören zur Wortfamilie '-ight'?", options: ["bright, fight, right", "bit, fit, sit", "boat, coat, goat", "run, fun, sun"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_5_e3", topicId: 5, prompt: "Welches Wort reimt mit 'cake'?", options: ["back", "lake", "kick", "lock"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_5_e4", topicId: 5, prompt: "Welches Wort reimt NICHT mit 'ball'?", options: ["fall", "tall", "wall", "bell"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_5_e5", topicId: 5, prompt: "Was haben alle Wörter einer Wortfamilie gemeinsam?", options: ["Denselben Anfangsbuchstaben", "Dieselbe Bedeutung", "Dasselbe Endmuster", "Dieselbe Anzahl an Buchstaben"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_e6", topicId: 5, prompt: "Welches Wort reimt mit 'stone'?", options: ["ton", "tan", "bone", "tin"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_e7", topicId: 5, prompt: "Welche Wörter gehören zur Wortfamilie '-ack'?", options: ["back, pack, track", "bit, sit, fit", "can, man, tan", "hop, top, mop"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_5_e8", topicId: 5, prompt: "Welches Wort reimt mit 'tree'?", options: ["try", "trip", "three", "trick"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_5_e9", topicId: 5, prompt: "Welches Wort reimt NICHT mit 'day'?", options: ["play", "say", "way", "dip"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_5_e10", topicId: 5, prompt: "Welche Wörter gehören zur Wortfamilie '-ake'?", options: ["cake, lake, make", "bit, sit, pit", "hot, dot, lot", "run, fun, bun"], correctIndex: 0)
    ],
    6: [
        MathExamQuestion(id: "de_teach_6_e1", topicId: 6, prompt: "Welches Wortpaar zeigt den Unterschied zwischen kurzem und langem Vokal?", options: ["cat / dog", "cap / cape", "run / fun", "sit / bit"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_e2", topicId: 6, prompt: "Was passiert, wenn man ein 'e' an 'pin' anhängt?", options: ["Der 'i'-Laut wird kurz.", "Der 'i'-Laut wird lang (pine).", "Das Wort ändert den Konsonanten.", "Das Wort wird kürzer."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_6_e3", topicId: 6, prompt: "Welches Wort hat einen langen 'a'-Laut?", options: ["hand", "land", "sand", "plane"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_6_e4", topicId: 6, prompt: "Was bedeutet 'cute' auf Deutsch?", options: ["groß", "laut", "süß/niedlich", "schnell"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_e5", topicId: 6, prompt: "Welches Wort folgt der stummen E-Regel und hat einen langen Vokal?", options: ["stop", "hop", "note", "drop"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_e6", topicId: 6, prompt: "Was bedeutet 'home' auf Deutsch?", options: ["Heim/Zuhause", "Hoffnung", "Hügel", "Loch"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_6_e7", topicId: 6, prompt: "Welches Wort hat einen langen 'i'-Laut?", options: ["fin", "spin", "win", "shine"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_6_e8", topicId: 6, prompt: "Welches Wort hat einen langen 'e'-Laut?", options: ["pet", "set", "net", "theme"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_6_e9", topicId: 6, prompt: "Was entsteht aus 'tub' wenn man ein stummes 'e' anhängt?", options: ["tubs", "tubing", "tube", "tuber"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_6_e10", topicId: 6, prompt: "Welches Wort hat KEINEN langen Vokal?", options: ["make", "time", "bone", "fun"], correctIndex: 3)
    ],
    7: [
        MathExamQuestion(id: "de_teach_7_e1", topicId: 7, prompt: "Welches Wort beginnt mit dem Blend 'cl'?", options: ["chair", "think", "cloud", "sheep"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_e2", topicId: 7, prompt: "Was ist der Unterschied zwischen einem Blend und einem Digraph?", options: ["Es gibt keinen Unterschied", "Beim Blend hört man beide Laute, beim Digraph entsteht ein neuer Laut", "Beim Digraph hört man beide Laute", "Blends haben immer drei Buchstaben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_e3", topicId: 7, prompt: "Welches Wort enthält den Digraphen 'ph'?", options: ["ship", "chip", "photo", "thin"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_e4", topicId: 7, prompt: "Welcher Blend steckt am Anfang von 'bread'?", options: ["bl", "br", "tr", "dr"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_e5", topicId: 7, prompt: "Welches Wort beginnt mit dem Digraphen 'ch'?", options: ["ship", "think", "where", "cheese"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_7_e6", topicId: 7, prompt: "Welcher Blend steckt am Anfang von 'sleep'?", options: ["sp", "st", "sl", "sm"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_7_e7", topicId: 7, prompt: "Welches Wort enthält den Digraphen 'sh' am Ende?", options: ["think", "brush", "chair", "where"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_e8", topicId: 7, prompt: "Welcher Blend steckt am Anfang von 'grass'?", options: ["gr", "br", "pr", "tr"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_7_e9", topicId: 7, prompt: "Wie viele Laute hört man beim Digraph 'th' in 'think'?", options: ["0", "1", "2", "3"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_7_e10", topicId: 7, prompt: "Welches Wort beginnt mit dem Blend 'fr'?", options: ["three", "flower", "frog", "string"], correctIndex: 2)
    ],
    8: [
        MathExamQuestion(id: "de_teach_8_e1", topicId: 8, prompt: "Was ist der Plural von 'mouse' im Englischen?", options: ["mouses", "mouse", "mice", "mousen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_e2", topicId: 8, prompt: "Welches Wort ist ein Verb?", options: ["happiness", "teacher", "elephant", "dance"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_8_e3", topicId: 8, prompt: "Was ist der Plural von 'tooth'?", options: ["tooths", "teeths", "teeth", "tooth"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_e4", topicId: 8, prompt: "Was bedeutet 'to fly' auf Deutsch?", options: ["fliegen", "fallen", "fühlen", "finden"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_8_e5", topicId: 8, prompt: "Welches Wort ist ein konkretes Nomen (man kann es anfassen)?", options: ["happiness", "freedom", "book", "idea"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_e6", topicId: 8, prompt: "Wie bildet man normalerweise den Plural bei englischen Nomen?", options: ["Man fügt '-es' hinzu", "Man fügt '-s' hinzu", "Man ändert den Vokal", "Man fügt '-en' hinzu"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_e7", topicId: 8, prompt: "Was ist das Verb im Satz 'The birds sing beautifully'?", options: ["birds", "sing", "beautifully", "the"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_e8", topicId: 8, prompt: "Was ist der Plural von 'leaf'?", options: ["leafs", "leaves", "leaf", "leaven"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_8_e9", topicId: 8, prompt: "Welches Wort ist ein Nomen das einen Ort beschreibt?", options: ["run", "beautiful", "park", "quickly"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_8_e10", topicId: 8, prompt: "Was bedeutet 'to sleep' auf Deutsch?", options: ["springen", "schlafen", "spielen", "sprechen"], correctIndex: 1)
    ],
    9: [
        MathExamQuestion(id: "de_teach_9_e1", topicId: 9, prompt: "Was ist die Superlativform von 'happy'?", options: ["more happy", "happiest", "most happy", "happyer"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e2", topicId: 9, prompt: "Welches Adverb passt? 'The turtle moves ___.'", options: ["fast", "slowly", "loud", "bright"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e3", topicId: 9, prompt: "Was ist die Komparativform von 'cold'?", options: ["coldest", "more cold", "colder", "most cold"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_e4", topicId: 9, prompt: "Welches Adjektiv beschreibt die Form?", options: ["loud", "round", "quickly", "sadly"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e5", topicId: 9, prompt: "Welches Adverb passt? 'She sang the song ___.'", options: ["beautiful", "beautifully", "beauty", "beautify"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e6", topicId: 9, prompt: "Was bedeutet 'noisily' auf Deutsch?", options: ["leise", "laut/lärmend", "langsam", "schnell"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e7", topicId: 9, prompt: "Welches Adjektiv passt? 'The ___ elephant drank water.'", options: ["quickly", "thirsty", "slowly", "loudly"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e8", topicId: 9, prompt: "Was ist die Superlativform von 'tall'?", options: ["taller", "tallest", "most tall", "more tall"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_9_e9", topicId: 9, prompt: "Welches dieser Wörter ist ein Adverb?", options: ["green", "happy", "carefully", "child"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_9_e10", topicId: 9, prompt: "Welches Wort beschreibt WIE jemand spricht?", options: ["Ein Adjektiv", "Ein Nomen", "Ein Adverb", "Ein Pronomen"], correctIndex: 2)
    ],
    10: [
        MathExamQuestion(id: "de_teach_10_e1", topicId: 10, prompt: "Welcher Satz ist korrekt interpunktiert?", options: ["Did you see the movie", "Did you see the movie?", "Did you see the movie!", "Did you see the movie,"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_e2", topicId: 10, prompt: "Wo steht ein Komma in einer Aufzählung?", options: ["Am Ende jedes Wortes", "Zwischen den Einträgen", "Am Anfang der Liste", "Gar nicht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_e3", topicId: 10, prompt: "Welches Satzzeichen verwendet man bei der direkten Rede?", options: ["Punkt", "Komma", "Anführungszeichen", "Apostroph"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_e4", topicId: 10, prompt: "Welcher Satz hat einen Fehler bei der Großschreibung?", options: ["My name is Tim.", "i like pizza.", "London is big.", "She is happy."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_e5", topicId: 10, prompt: "Welches Satzzeichen fehlt am Ende? 'Watch out'", options: [".", "?", "!", ","], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_e6", topicId: 10, prompt: "In welchem Satz wird das Komma falsch verwendet?", options: ["I have a cat, a dog, and a fish.", "I went to the store, and I bought milk.", "I like, cats.", "Please sit down, Tom."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_e7", topicId: 10, prompt: "Was zeigt ein Apostroph in 'Sarah's book'?", options: ["Plural", "Kontraktion", "Besitz", "Auslassung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_e8", topicId: 10, prompt: "Welcher Satz braucht kein Ausrufezeichen?", options: ["Help me!", "Fire! Run!", "I eat breakfast.", "Wow, that's amazing!"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_10_e9", topicId: 10, prompt: "Was fehlt im Satz? 'My favorite animals are cats dogs and birds.'", options: ["Ausrufezeichen", "Kommas zwischen den Tieren", "Ein Fragezeichen", "Großbuchstaben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_10_e10", topicId: 10, prompt: "Welcher Satz ist vollständig korrekt interpunktiert?", options: ["the cat sat on the mat", "The cat sat on the mat", "The cat sat on the mat.", "the cat sat on the mat."], correctIndex: 2)
    ],
    11: [
        MathExamQuestion(id: "de_teach_11_e1", topicId: 11, prompt: "Welche zwei Wörter bilden 'bedroom'?", options: ["bed + room", "bee + room", "red + boom", "bed + broom"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_e2", topicId: 11, prompt: "Was ist die Langform von \"he's\"?", options: ["he was", "he is", "he has", "Sowohl 'he is' als auch 'he has'"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_11_e3", topicId: 11, prompt: "Welches ist ein zusammengesetztes Wort?", options: ["quickly", "unhappy", "bookshelf", "playing"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_11_e4", topicId: 11, prompt: "Was ist die Langform von \"won't\"?", options: ["would not", "will not", "was not", "were not"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_11_e5", topicId: 11, prompt: "Welche zwei Wörter bilden 'toothbrush'?", options: ["too + brush", "tooth + rush", "tooth + brush", "toot + brush"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_11_e6", topicId: 11, prompt: "Was ist die Kurzform von 'we are'?", options: ["we're", "were", "wear", "we'are"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_e7", topicId: 11, prompt: "Welche zwei Wörter bilden 'snowflake'?", options: ["snow + flake", "show + lake", "snow + lake", "slow + fake"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_e8", topicId: 11, prompt: "Was ist die Langform von \"she'll\"?", options: ["she will", "she was", "she is", "she had"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_11_e9", topicId: 11, prompt: "Welches ist KEIN zusammengesetztes Wort?", options: ["butterfly", "sunflower", "beautiful", "doorbell"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_11_e10", topicId: 11, prompt: "Was ist die Kurzform von 'it is'?", options: ["its", "it's", "its'", "i'ts"], correctIndex: 1)
    ],
    12: [
        MathExamQuestion(id: "de_teach_12_e1", topicId: 12, prompt: "Was bedeutet 'unkind'?", options: ["sehr freundlich", "nicht freundlich", "wieder freundlich", "überaus freundlich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_e2", topicId: 12, prompt: "Welches Wort enthält die Nachsilbe '-less'?", options: ["joyful", "joyless", "enjoy", "rejoice"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_e3", topicId: 12, prompt: "Was bedeutet 'rebuild'?", options: ["nicht bauen", "sehr schnell bauen", "wieder aufbauen", "vor dem Bauen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_e4", topicId: 12, prompt: "Was wird aus 'happy' mit der Nachsilbe '-er' bei der Steigerung?", options: ["happyer", "happier", "more happy", "happiest"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_e5", topicId: 12, prompt: "Was bedeutet die Nachsilbe '-less'?", options: ["voll von", "ohne", "wieder", "sehr"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_12_e6", topicId: 12, prompt: "Welches Wort hat die Vorsilbe 'pre-' (vor)?", options: ["rewrite", "unhappy", "preview", "careful"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_e7", topicId: 12, prompt: "Was bedeutet 'powerful'?", options: ["ohne Kraft", "sehr langsam", "kraftvoll/mächtig", "wieder stark"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_e8", topicId: 12, prompt: "Welches Wort hat die Nachsilbe '-ed' als Vergangenheitsform?", options: ["plays", "playing", "played", "player"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_e9", topicId: 12, prompt: "Was bedeutet 'misunderstand'? (mis- = falsch)", options: ["richtig verstehen", "wieder verstehen", "falsch verstehen", "nicht verstehen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_12_e10", topicId: 12, prompt: "Welches Wort enthält KEINE Vor- oder Nachsilbe?", options: ["unhappy", "remake", "beautiful", "table"], correctIndex: 3)
    ],
    13: [
        MathExamQuestion(id: "de_teach_13_e1", topicId: 13, prompt: "Was ist ein Synonym für 'pretty'?", options: ["ugly", "beautiful", "sad", "angry"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_13_e2", topicId: 13, prompt: "Was ist das Antonym von 'light' (leicht)?", options: ["bright", "dark", "heavy", "thin"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e3", topicId: 13, prompt: "Was ist ein Synonym für 'tired'?", options: ["awake", "energetic", "exhausted", "happy"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e4", topicId: 13, prompt: "Was ist das Antonym von 'young'?", options: ["new", "small", "little", "old"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_13_e5", topicId: 13, prompt: "Was ist ein Synonym für 'look'?", options: ["listen", "touch", "see", "smell"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e6", topicId: 13, prompt: "Was ist das Antonym von 'love'?", options: ["like", "enjoy", "hate", "care"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e7", topicId: 13, prompt: "Was ist ein Synonym für 'cold'?", options: ["warm", "hot", "freezing", "mild"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e8", topicId: 13, prompt: "Was ist das Antonym von 'above'?", options: ["over", "up", "below", "on"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e9", topicId: 13, prompt: "Was ist ein Synonym für 'talk'?", options: ["listen", "hear", "speak", "read"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_13_e10", topicId: 13, prompt: "Was ist das Antonym von 'remember'?", options: ["recall", "think", "forget", "know"], correctIndex: 2)
    ],
    14: [
        MathExamQuestion(id: "de_teach_14_e1", topicId: 14, prompt: "Lies: 'Anna has a cat. The cat is orange. It sleeps all day.' Was ist die Hauptidee?", options: ["Anna hat einen Hund.", "Anna hat eine orangene Katze die viel schläft.", "Katzen sind orange.", "Katzen schlafen nicht."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e2", topicId: 14, prompt: "Was bedeutet 'inference' (Schlussfolgerung) beim Lesen?", options: ["Wörter buchstabieren", "Etwas erschließen was nicht direkt gesagt wird", "Laut vorlesen", "Den Text abschreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e3", topicId: 14, prompt: "Welche Frage hilft beim Verstehen des Settings einer Geschichte?", options: ["Wer ist die Hauptfigur?", "Was ist das Problem?", "Wo und wann spielt die Geschichte?", "Wie endet die Geschichte?"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_e4", topicId: 14, prompt: "Was ist der Unterschied zwischen Fakt und Meinung in einem Text?", options: ["Es gibt keinen Unterschied", "Fakten sind beweisbar, Meinungen sind persönliche Ansichten", "Meinungen sind immer richtig", "Fakten sind immer falsch"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e5", topicId: 14, prompt: "Lies: 'Tom ran to school. He was late.' Warum ist Tom gerannt?", options: ["Weil er Sport mochte.", "Weil er zu spät war.", "Weil es regnete.", "Weil seine Mutter es sagte."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e6", topicId: 14, prompt: "Was ist ein 'Textbeleg' (text evidence)?", options: ["Eine Meinung zum Text", "Eine Stelle im Text die eine Antwort unterstützt", "Eine Zusammenfassung", "Ein neues Wort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e7", topicId: 14, prompt: "Welche Strategie hilft beim Lesen unbekannter Wörter?", options: ["Das Wort überspringen", "Den Text abbrechen", "Den Kontext (Zusammenhang) nutzen", "Das Wort laut buchstabieren"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_e8", topicId: 14, prompt: "Was zeigt uns die 'Überschrift' (title) eines Textes?", options: ["Das Ende des Textes", "Den Autor", "Worum es im Text geht", "Die Satzzeichen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_14_e9", topicId: 14, prompt: "Was bedeutet 'to summarize' (zusammenfassen) auf Deutsch?", options: ["Den Text Wort für Wort lesen", "Die wichtigsten Ideen mit eigenen Worten wiedergeben", "Neue Details erfinden", "Den Text laut vorlesen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_14_e10", topicId: 14, prompt: "Welche Frage hilft, die Hauptidee zu finden?", options: ["Worum geht es hauptsächlich in diesem Text?", "Was ist das erste Wort?", "Wie viele Sätze hat der Text?", "Wer hat den Text geschrieben?"], correctIndex: 0)
    ],
    15: [
        MathExamQuestion(id: "de_teach_15_e1", topicId: 15, prompt: "Was beschreibt den 'Höhepunkt' (climax) einer Geschichte?", options: ["Den Anfang der Geschichte", "Den spannendsten oder wichtigsten Moment", "Das Ende der Geschichte", "Die Einführung der Figuren"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_e2", topicId: 15, prompt: "Was ist der Unterschied zwischen Haupt- und Nebenfigur?", options: ["Es gibt keinen Unterschied", "Die Hauptfigur ist wichtiger und erscheint öfter", "Die Nebenfigur ist wichtiger", "Beide erscheinen gleich oft"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_e3", topicId: 15, prompt: "Was ist ein 'Antagonist' in einer Geschichte?", options: ["Der Held der Geschichte", "Die Person oder Kraft die dem Helden entgegenwirkt", "Der Erzähler", "Die Nebenfigur"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_e4", topicId: 15, prompt: "Was beschreibt der 'Erzählpunkt' (point of view)?", options: ["Den Ort der Geschichte", "Die Zeit der Geschichte", "Aus wessen Perspektive die Geschichte erzählt wird", "Das Problem der Geschichte"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_e5", topicId: 15, prompt: "Was ist ein 'Konflikt' (conflict) in einer Geschichte?", options: ["Das glückliche Ende", "Das Setting der Geschichte", "Die Einführung der Figuren", "Das Problem oder der Kampf in der Geschichte"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_15_e6", topicId: 15, prompt: "Was passiert in der 'Auflösung' (resolution) einer Geschichte?", options: ["Das Problem beginnt", "Neue Figuren erscheinen", "Das Problem wird gelöst und die Geschichte endet", "Das Setting ändert sich"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_e7", topicId: 15, prompt: "Was ist ein 'Protagonist'?", options: ["Der Bösewicht", "Der Hauptheld der Geschichte", "Der Erzähler", "Eine Nebenfigur"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_e8", topicId: 15, prompt: "Was beschreibt das Setting einer Geschichte?", options: ["Die Handlungen der Figuren", "Ort, Zeit und Atmosphäre der Geschichte", "Das Problem der Geschichte", "Die Moral der Geschichte"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_15_e9", topicId: 15, prompt: "Was ist ein 'Thema' (theme) in einer Geschichte?", options: ["Die Hauptfigur", "Der Ort der Geschichte", "Die zentrale Botschaft oder Lektion", "Das Problem"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_15_e10", topicId: 15, prompt: "In welcher Reihenfolge treten diese Geschichtselemente typischerweise auf?", options: ["Lösung → Problem → Setting → Figuren", "Figuren → Setting → Problem → Lösung", "Problem → Figuren → Setting → Lösung", "Setting → Lösung → Figuren → Problem"], correctIndex: 1)
    ],
    16: [
        MathExamQuestion(id: "de_teach_16_e1", topicId: 16, prompt: "Welcher Satz ist ein Aussagesatz?", options: ["Where is the library?", "Go to the library.", "The library is on Main Street.", "What a great library!"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_e2", topicId: 16, prompt: "Welcher Satz ist ein Aufforderungssatz (Imperativ)?", options: ["Is the door open?", "The door is open.", "Open the door.", "What an open door!"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_e3", topicId: 16, prompt: "Mit welchem Wort beginnen oft englische Fragesätze?", options: ["The, A, An", "Do, Does, Is, Are, Can, What, Where", "I, We, They, He", "Run, Jump, Play"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_16_e4", topicId: 16, prompt: "Welcher Satz drückt eine starke Emotion aus?", options: ["The sky is blue.", "Is the sky blue?", "Look at the blue sky.", "What a beautiful blue sky!"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_16_e5", topicId: 16, prompt: "Was ist der Unterschied zwischen Aufforderungssatz und Aussagesatz?", options: ["Es gibt keinen Unterschied", "Der Aussagesatz fordert auf, der Aufforderungssatz behauptet", "Der Aufforderungssatz gibt eine Anweisung, der Aussagesatz behauptet etwas", "Der Fragesatz und Aussagesatz sind gleich"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_e6", topicId: 16, prompt: "Welcher Satz ist ein Fragesatz?", options: ["I can swim.", "Can you swim?", "Swim fast!", "What a swimmer!"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_16_e7", topicId: 16, prompt: "Mit welchem Satzzeichen endet ein Ausrufesatz?", options: [".", "?", ",", "!"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_16_e8", topicId: 16, prompt: "Welcher Satz ist grammatikalisch korrekt als Frage?", options: ["You like pizza do?", "Like you pizza?", "Do you like pizza?", "Pizza you like?"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_16_e9", topicId: 16, prompt: "Was ist besonders am Aufforderungssatz im Englischen?", options: ["Er beginnt immer mit 'I'", "Das Subjekt 'you' ist oft weggelassen", "Er endet immer mit '?'", "Er beginnt immer mit 'they'"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_16_e10", topicId: 16, prompt: "Welche Satzart ist dies? 'Please close the window.'", options: ["Aussagesatz", "Fragesatz", "Ausrufesatz", "Aufforderungssatz"], correctIndex: 3)
    ],
    17: [
        MathExamQuestion(id: "de_teach_17_e1", topicId: 17, prompt: "Welches Wort passt? 'Put the book over ___.' (Leg das Buch dort drüben hin.)", options: ["their", "they're", "there", "they"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e2", topicId: 17, prompt: "Welches Wort passt? 'I have ___ cats.' (Ich habe zwei Katzen.)", options: ["to", "too", "two", "tow"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e3", topicId: 17, prompt: "Welches Wort passt? '___ house is very big.' (Ihr Haus ist sehr groß.)", options: ["They're", "There", "Their", "Theirs"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e4", topicId: 17, prompt: "Was bedeutet 'it's' im Englischen?", options: ["seine/ihre (Besitz)", "it is / it has (Kontraktion)", "das Tier", "das Ding"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_17_e5", topicId: 17, prompt: "Welches Wort passt? 'I want to come, ___.' (Ich möchte auch kommen.)", options: ["to", "two", "too", "tow"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e6", topicId: 17, prompt: "Was ist der Unterschied zwischen 'its' und 'it's'?", options: ["Es gibt keinen Unterschied", "'its' zeigt Besitz, 'it's' ist eine Kontraktion von 'it is'", "'it's' zeigt Besitz, 'its' ist eine Kontraktion", "Beide sind Kontraktionen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_17_e7", topicId: 17, prompt: "Welches Wort passt? 'I am going ___ school.' (Ich gehe zur Schule.)", options: ["too", "two", "to", "tow"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e8", topicId: 17, prompt: "Welches Wort passt? '___ happy today.' (Sie sind heute glücklich.)", options: ["There", "Their", "They're", "Theyre"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_17_e9", topicId: 17, prompt: "Was ist ein Homonym?", options: ["Ein Synonym", "Ein Wort das gleich klingt aber unterschiedlich geschrieben wird", "Ein Antonym", "Ein zusammengesetztes Wort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_17_e10", topicId: 17, prompt: "Welches Wort passt? 'Is this ___ bag?' (Ist das deine Tasche?)", options: ["you're", "your", "you are", "yore"], correctIndex: 1)
    ],
    18: [
        MathExamQuestion(id: "de_teach_18_e1", topicId: 18, prompt: "Welche Wortart ist 'on' im Satz 'The cat sits on the mat'?", options: ["Nomen", "Verb", "Adjektiv", "Präposition"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_18_e2", topicId: 18, prompt: "Welches Pronomen ersetzt 'Maria' im Satz?", options: ["he", "it", "she", "they"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_e3", topicId: 18, prompt: "Was ist eine Konjunktion (conjunction) im Englischen?", options: ["Ein Beschreibungswort", "Ein Verbindungswort wie 'and', 'but', 'or'", "Ein Nomen", "Eine Handlung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_18_e4", topicId: 18, prompt: "Welche Wortart ist 'between' im Satz 'The ball is between the chairs'?", options: ["Nomen", "Verb", "Präposition", "Pronomen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_e5", topicId: 18, prompt: "Welches Wort ist ein Personalpronomen?", options: ["happy", "run", "they", "school"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_e6", topicId: 18, prompt: "Welche Wortart ist 'but' im Satz 'I like cats but not dogs'?", options: ["Pronomen", "Präposition", "Konjunktion", "Adverb"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_e7", topicId: 18, prompt: "Was ist ein Artikel (article) im Englischen?", options: ["'a', 'an', 'the'  -  Wörter vor Nomen", "Ein Verb", "Ein Pronomen", "Ein Adverb"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_18_e8", topicId: 18, prompt: "Welche Wortart ist 'we' im Satz 'We love football'?", options: ["Nomen", "Pronomen", "Verb", "Adjektiv"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_18_e9", topicId: 18, prompt: "Welches Wort ist eine Präposition?", options: ["run", "happy", "behind", "she"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_18_e10", topicId: 18, prompt: "In dem Satz 'She quickly ran to the big park'  -  welches Wort ist das Adjektiv?", options: ["quickly", "ran", "big", "She"], correctIndex: 2)
    ]
]
