import Foundation

// MARK: - English Teaching Pack: German (Topics 19-35)

let deTeachingTopicsB: [(id: Int, title: String, intro: String, example: String)] = [
    (19, "Subjekt und Prädikat", "Jeder englische Satz hat ein Subjekt (wer/was) und ein Prädikat (was getan wird).", "In 'The dog runs fast' ist 'The dog' das Subjekt und 'runs fast' das Prädikat."),
    (20, "Bildhafte Sprache", "Bildhafte Sprache verwendet Wörter nicht wörtlich, um lebhafte Bilder zu erzeugen.", "Simile: 'brave as a lion'. Metapher: 'time is money'. Personifikation: 'the wind whispered'."),
    (21, "Vokabular im Kontext", "Du kannst die Bedeutung unbekannter englischer Wörter durch Kontexthinweise herausfinden.", "In 'She was famished  -  she hadn't eaten all day' bedeutet 'famished' sehr hungrig."),
    (22, "Hauptidee", "Die Hauptidee ist die wichtigste Aussage eines Absatzes. Stützende Details erklären sie.", "In einem Absatz über Hunde könnte die Hauptidee sein: 'Dogs are loyal pets.'"),
    (23, "Erzählperspektive", "Die Erzählperspektive zeigt, aus welcher Sichtweise eine Geschichte erzählt wird.", "Erste Person: I/me. Zweite Person: you. Dritte Person: he/she/they."),
    (24, "Textstrukturen", "Englische Texte haben verschiedene Strukturen: Vergleich, Ursache/Wirkung, Problem/Lösung.", "Signalwörter für Ursache/Wirkung: 'because', 'therefore', 'as a result'."),
    (25, "Erzählendes Schreiben", "Eine englische Erzählung hat Anfang, Mitte und Ende sowie Charaktere und einen Konflikt.", "Dialogzeichen in Englisch: 'Hello,' said Maria. 'How are you?'"),
    (26, "Englische Lyrik", "Englische Gedichte haben Reimschemata, Strophen und Stilmittel wie Alliteration.", "ABAB-Reimschema: Zeile 1 reimt mit 3, Zeile 2 reimt mit 4."),
    (27, "Zusammengesetzte Sätze", "FANBOYS-Konjunktionen verbinden zwei Hauptsätze: for, and, nor, but, or, yet, so.", "'I was tired, but I finished my homework.'  -  'but' verbindet zwei Hauptsätze."),
    (28, "Aktiv und Passiv", "Im Aktiv handelt das Subjekt. Im Passiv empfängt das Subjekt die Handlung.", "Aktiv: 'The cat chased the mouse.' Passiv: 'The mouse was chased by the cat.'"),
    (29, "Überzeugend Schreiben", "Überzeugender Text enthält eine These, Beweise und rhetorische Mittel (Ethos, Pathos, Logos).", "Logos (Logik): Fakten und Statistiken. Pathos (Gefühl): emotionale Appelle."),
    (30, "Literarische Mittel", "Englische Literatur verwendet Stilmittel wie Vorausdeutung, Ironie und Symbolismus.", "Symbolismus: Eine weiße Taube symbolisiert Frieden. Ironie: Das Gegenteil wird gesagt."),
    (31, "Autorenabsicht", "Ein Autor schreibt, um zu informieren, zu überzeugen oder zu unterhalten.", "Wenn ein Text Fakten erklärt, ist die Absicht 'to inform'. Bei Werbung: 'to persuade'."),
    (32, "Recherche und Zitate", "Beim Schreiben auf Englisch musst du Quellen korrekt zitieren und Plagiate vermeiden.", "MLA-Format: Author Last, First. 'Title.' Publisher, Year."),
    (33, "Shakespeare und Klassische Literatur", "Shakespeare schrieb Tragödien, Komödien und Sonette im elisabethanischen Englisch.", "Jambischer Pentameter: 10 Silben pro Zeile, abwechselnd unbetont/betont."),
    (34, "Etymologie", "Viele englische Wörter haben lateinische oder griechische Wurzeln.", "bio = Leben (biology), geo = Erde (geography), port = tragen (transport)."),
    (35, "Fortgeschrittene Grammatik", "Fortgeschrittene englische Grammatik umfasst Semikolon, Doppelpunkt und Parallelismus.", "Semikolon verbindet zwei verwandte Hauptsätze: 'I love English; it opens doors.'")
]

let deTeachingPracticeB: [Int: [MathExamQuestion]] = [
    19: [
        MathExamQuestion(id: "de_teach_19_p1", topicId: 19, prompt: "Was ist das Subjekt in 'The birds sing beautifully'?", options: ["sing", "beautifully", "The birds", "The birds sing"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_p2", topicId: 19, prompt: "Was ist das Prädikat in 'My sister reads books'?", options: ["My sister", "books", "reads books", "My sister reads"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_p3", topicId: 19, prompt: "Welches ist ein vollständiger englischer Satz?", options: ["The big dog.", "Running fast.", "She sings well.", "Under the tree."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_p4", topicId: 19, prompt: "Was ist das Subjekt in 'They played football yesterday'?", options: ["football", "played", "yesterday", "They"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_19_p5", topicId: 19, prompt: "Welcher Satzteil sagt uns, WAS das Subjekt tut?", options: ["Das Subjekt", "Das Prädikat", "Das Objekt", "Die Präposition"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_p6", topicId: 19, prompt: "Was ist das Subjekt in 'The old man walks slowly'?", options: ["walks", "slowly", "The old man", "walks slowly"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_p7", topicId: 19, prompt: "Welcher Satz hat ein zusammengesetztes Subjekt?", options: ["She runs fast.", "Tom and Lisa play.", "He sleeps.", "The dog barks."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_p8", topicId: 19, prompt: "Was ist das Prädikat in 'The children are happy'?", options: ["The children", "happy", "are happy", "children are"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_p9", topicId: 19, prompt: "Welcher Satz fehlt das Subjekt?", options: ["Birds fly south.", "Runs very fast.", "She likes cats.", "We eat lunch."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_p10", topicId: 19, prompt: "Was ist das Subjekt in 'Every morning, the sun rises'?", options: ["Every morning", "rises", "the sun", "morning"], correctIndex: 2)
    ],
    20: [
        MathExamQuestion(id: "de_teach_20_p1", topicId: 20, prompt: "Welche Art von Stilmittel ist 'Her voice is music to my ears'?", options: ["Simile", "Metapher", "Personifikation", "Hyperbel"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_p2", topicId: 20, prompt: "Welche Art von Stilmittel ist 'He ran as fast as a cheetah'?", options: ["Metapher", "Simile", "Personifikation", "Ironie"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_p3", topicId: 20, prompt: "Welche Art von Stilmittel ist 'The stars winked at me'?", options: ["Simile", "Hyperbel", "Personifikation", "Metapher"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_20_p4", topicId: 20, prompt: "Welche Art von Stilmittel ist 'I'm so hungry I could eat a horse'?", options: ["Simile", "Metapher", "Personifikation", "Hyperbel"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_20_p5", topicId: 20, prompt: "Ein Simile verwendet welche Wörter für den Vergleich?", options: ["is / are", "like / as", "was / were", "has / have"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_p6", topicId: 20, prompt: "Welche Art von Stilmittel ist 'Life is a journey'?", options: ["Simile", "Metapher", "Personifikation", "Hyperbel"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_p7", topicId: 20, prompt: "Welche Art von Stilmittel ist 'The wind sang through the trees'?", options: ["Hyperbel", "Simile", "Metapher", "Personifikation"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_20_p8", topicId: 20, prompt: "Was ist der Unterschied zwischen Simile und Metapher?", options: ["Kein Unterschied", "Simile verwendet 'like' oder 'as', Metapher nicht", "Metapher verwendet 'like' oder 'as', Simile nicht", "Nur Metaphern sind bildlich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_p9", topicId: 20, prompt: "Welche Art von Stilmittel ist 'I've told you a million times'?", options: ["Metapher", "Personifikation", "Hyperbel", "Simile"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_20_p10", topicId: 20, prompt: "Welche Art von Stilmittel ist 'She is as brave as a lion'?", options: ["Metapher", "Simile", "Personifikation", "Hyperbel"], correctIndex: 1)
    ],
    21: [
        MathExamQuestion(id: "de_teach_21_p1", topicId: 21, prompt: "Was bedeutet 'jovial' in: 'He was jovial, always laughing and telling jokes'?", options: ["traurig", "fröhlich", "wütend", "schüchtern"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_p2", topicId: 21, prompt: "Was bedeutet 'enormous' in: 'The enormous elephant crushed the tiny tree'?", options: ["winzig", "schnell", "riesig", "laut"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_p3", topicId: 21, prompt: "Was ist ein Kontexthinweis?", options: ["Ein Wörterbuch", "Wörter um ein unbekanntes Wort herum", "Die erste Zeile eines Textes", "Der Titel des Textes"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_p4", topicId: 21, prompt: "Was bedeutet 'drenched' in: 'We got drenched in the rain  -  completely soaked'?", options: ["trocken", "kalt", "völlig nass", "verloren"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_p5", topicId: 21, prompt: "Was bedeutet 'swift' in: 'The swift horse galloped across the field'?", options: ["langsam", "groß", "schnell", "alt"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_p6", topicId: 21, prompt: "Was bedeutet 'ancient' in: 'The ancient ruins were thousands of years old'?", options: ["neu", "uralt", "klein", "bekannt"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_p7", topicId: 21, prompt: "Was bedeutet 'reluctant' in: 'She was reluctant to go; she kept making excuses'?", options: ["begeistert", "müde", "widerwillig", "bereit"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_p8", topicId: 21, prompt: "Was bedeutet 'scorching' in: 'The scorching sun burned our skin'?", options: ["kalt", "bewölkt", "sehr heiß", "feucht"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_p9", topicId: 21, prompt: "Was bedeutet 'peculiar' in: 'The peculiar smell was unlike anything we'd encountered'?", options: ["angenehm", "seltsam", "bekannt", "stark"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_p10", topicId: 21, prompt: "Was bedeutet 'weary' in: 'After the long hike, we were weary and needed rest'?", options: ["hungrig", "glücklich", "erschöpft", "aufgeregt"], correctIndex: 2)
    ],
    22: [
        MathExamQuestion(id: "de_teach_22_p1", topicId: 22, prompt: "Was ist die Hauptidee eines Absatzes?", options: ["Das erste Wort", "Die wichtigste Aussage", "Der letzte Satz", "Ein Detail"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_p2", topicId: 22, prompt: "Was sind 'supporting details' auf Englisch?", options: ["Hauptaussagen", "Details, die die Hauptidee erklären", "Titel", "Schlussfolgerungen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_p3", topicId: 22, prompt: "Wo steht die Hauptidee oft in einem Absatz?", options: ["Immer in der Mitte", "Nur am Ende", "Oft im ersten oder letzten Satz", "Nie im Text"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_22_p4", topicId: 22, prompt: "Ein Absatz handelt von Hunden. Was ist wahrscheinlich die Hauptidee?", options: ["Ein Hund heißt Rex.", "Hunde haben vier Beine.", "Hunde sind treue Haustiere.", "Hunde fressen Fleisch."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_22_p5", topicId: 22, prompt: "Was unterscheidet die Hauptidee von einem Detail?", options: ["Nichts", "Die Hauptidee ist allgemeiner", "Details sind allgemeiner", "Die Hauptidee ist kürzer"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_p6", topicId: 22, prompt: "Wie heißt der Eröffnungssatz eines Absatzes, der die Hauptidee enthält?", options: ["Conclusion", "Topic sentence", "Detail sentence", "Transition"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_p7", topicId: 22, prompt: "Welcher Satz ist eine Hauptidee (nicht ein Detail)?", options: ["Polar bears have white fur.", "Bears eat fish in rivers.", "Bears can run 30 mph.", "Bears are fascinating animals."], correctIndex: 3),
        MathExamQuestion(id: "de_teach_22_p8", topicId: 22, prompt: "Was macht ein stützendes Detail?", options: ["Widerspricht der Hauptidee", "Erklärt oder beweist die Hauptidee", "Beginnt den Absatz", "Beendet den Absatz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_p9", topicId: 22, prompt: "Wie heißt der abschließende Satz eines Absatzes?", options: ["Topic sentence", "Hook", "Concluding sentence", "Detail"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_22_p10", topicId: 22, prompt: "Ein Absatz hat eine Hauptidee und wie viele stützende Details?", options: ["Genau einen", "Keine", "Mehrere", "Immer zehn"], correctIndex: 2)
    ],
    23: [
        MathExamQuestion(id: "de_teach_23_p1", topicId: 23, prompt: "Welche Perspektive verwendet 'I' und 'me'?", options: ["Zweite Person", "Dritte Person", "Erste Person", "Vierte Person"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_p2", topicId: 23, prompt: "Welche Perspektive verwendet 'you'?", options: ["Erste Person", "Zweite Person", "Dritte Person", "Allwissend"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_p3", topicId: 23, prompt: "Welche Perspektive verwendet 'he', 'she', 'they'?", options: ["Erste Person", "Zweite Person", "Dritte Person", "Keine"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_p4", topicId: 23, prompt: "Aus welcher Perspektive ist 'I walked to school and saw my friend'?", options: ["Zweite Person", "Dritte Person", "Erste Person", "Allwissend"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_p5", topicId: 23, prompt: "Aus welcher Perspektive ist 'She opened the door and gasped'?", options: ["Erste Person", "Zweite Person", "Dritte Person", "Vierte Person"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_p6", topicId: 23, prompt: "Aus welcher Perspektive ist 'You are the hero of this story'?", options: ["Erste Person", "Zweite Person", "Dritte Person", "Allwissend"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_p7", topicId: 23, prompt: "Was ist der Vorteil der Ich-Perspektive (first person)?", options: ["Wir kennen alle Gedanken", "Wir kennen nur die Gedanken des Erzählers", "Kein Charakter hat Gefühle", "Der Erzähler ist unsichtbar"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_p8", topicId: 23, prompt: "Was ist der allwissende Erzähler (omniscient narrator)?", options: ["Erste Person", "Ein Erzähler, der alles weiß", "Zweite Person", "Ein unzuverlässiger Erzähler"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_p9", topicId: 23, prompt: "Aus welcher Perspektive ist 'We ran through the forest together'?", options: ["Zweite Person", "Dritte Person", "Erste Person Plural", "Allwissend"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_p10", topicId: 23, prompt: "Welches Pronomen zeigt dritte Person Einzahl weiblich?", options: ["I", "you", "she", "we"], correctIndex: 2)
    ],
    24: [
        MathExamQuestion(id: "de_teach_24_p1", topicId: 24, prompt: "Welche Textstruktur vergleicht zwei Dinge?", options: ["Ursache/Wirkung", "Problem/Lösung", "Vergleich/Kontrast", "Zeitfolge"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_p2", topicId: 24, prompt: "Welche Signalwörter zeigen Ursache/Wirkung an?", options: ["first, then, finally", "because, therefore, as a result", "however, but, on the other hand", "for example, such as"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_p3", topicId: 24, prompt: "Welche Textstruktur beschreibt Ereignisse in zeitlicher Reihenfolge?", options: ["Vergleich", "Problem/Lösung", "Ursache/Wirkung", "Chronologisch/Zeitfolge"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_24_p4", topicId: 24, prompt: "Welche Signalwörter zeigen Vergleich/Kontrast an?", options: ["because, so, therefore", "first, next, finally", "however, although, on the other hand", "for example, such as"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_p5", topicId: 24, prompt: "Ein Text erklärt ein Problem und bietet eine Lösung. Welche Struktur ist das?", options: ["Zeitfolge", "Vergleich", "Problem/Lösung", "Beschreibung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_p6", topicId: 24, prompt: "Welche Signalwörter zeigen Zeitfolge an?", options: ["however, but", "because, therefore", "first, then, next, finally", "similarly, likewise"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_p7", topicId: 24, prompt: "Ein Text beschreibt die Eigenschaften eines Tieres. Welche Struktur ist das?", options: ["Problem/Lösung", "Beschreibung", "Ursache/Wirkung", "Zeitfolge"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_p8", topicId: 24, prompt: "Was bedeutet 'therefore' auf Deutsch?", options: ["trotzdem", "deshalb/daher", "obwohl", "jedoch"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_p9", topicId: 24, prompt: "Welche Wörter zeigen Ähnlichkeit beim Vergleich an?", options: ["but, however, yet", "similarly, likewise, in the same way", "because, so, thus", "first, second, third"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_p10", topicId: 24, prompt: "Ein Text erklärt, warum es regnet. Welche Struktur ist das?", options: ["Vergleich", "Zeitfolge", "Ursache/Wirkung", "Problem/Lösung"], correctIndex: 2)
    ],
    25: [
        MathExamQuestion(id: "de_teach_25_p1", topicId: 25, prompt: "Was sind die drei Teile einer Erzählung auf Englisch?", options: ["Titel, Mitte, Schluss", "Anfang, Mitte, Ende", "Einleitung, These, Schluss", "Problem, Konflikt, Ironie"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p2", topicId: 25, prompt: "Wie werden Anführungszeichen im englischen Dialog gesetzt?", options: ["‚Hello,' said Tom.", "»Hello,« said Tom.", "'Hello,' said Tom.", "\"Hello,\" said Tom."], correctIndex: 3),
        MathExamQuestion(id: "de_teach_25_p3", topicId: 25, prompt: "Was ist der 'Konflikt' (conflict) in einer Geschichte?", options: ["Das Ende der Geschichte", "Das Problem des Charakters", "Der Hauptcharakter", "Der Ort der Geschichte"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p4", topicId: 25, prompt: "Welches Element kommt im Mittelteil einer Erzählung vor?", options: ["Einführung der Charaktere", "Höhepunkt und Spannungsaufbau", "Auflösung des Konflikts", "Einleitung des Schauplatzes"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p5", topicId: 25, prompt: "Was ist der 'climax' einer Geschichte?", options: ["Der Anfang", "Das Ende", "Der Höhepunkt der Spannung", "Die Einleitung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_25_p6", topicId: 25, prompt: "Was macht ein neuer Absatz beim Dialog?", options: ["Nichts Besonderes", "Zeigt einen neuen Sprecher an", "Beendet den Dialog", "Beginnt eine neue Geschichte"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p7", topicId: 25, prompt: "Was ist 'descriptive language' auf Deutsch?", options: ["Sachliche Sprache", "Beschreibende Sprache mit Details", "Einfache Sprache", "Formelle Sprache"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p8", topicId: 25, prompt: "Was ist die 'resolution' einer Geschichte?", options: ["Der Konflikt", "Die Auflösung des Problems", "Der Hauptcharakter", "Der Schauplatz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_p9", topicId: 25, prompt: "Was ist der 'setting' einer Geschichte?", options: ["Der Konflikt", "Die Hauptidee", "Ort und Zeit der Handlung", "Der Erzähler"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_25_p10", topicId: 25, prompt: "Was sind 'sensory details' in einer Erzählung?", options: ["Fakten und Statistiken", "Details, die die Sinne ansprechen", "Meinungen des Autors", "Schlussfolgerungen"], correctIndex: 1)
    ],
    26: [
        MathExamQuestion(id: "de_teach_26_p1", topicId: 26, prompt: "Was ist ein Reimschema (rhyme scheme)?", options: ["Die Länge eines Gedichts", "Das Muster der Reime in einem Gedicht", "Die Anzahl der Silben", "Der Titel des Gedichts"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p2", topicId: 26, prompt: "Was ist eine Strophe (stanza)?", options: ["Ein einzelnes Wort im Gedicht", "Ein Abschnitt/eine Gruppe von Versen", "Der Titel des Gedichts", "Das Reimschema"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p3", topicId: 26, prompt: "Was ist Alliteration?", options: ["Reimende Zeilenenden", "Wiederholung des Anfangskonsonanten", "Ein Vergleich mit 'like'", "Eine Übertreibung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p4", topicId: 26, prompt: "Beim ABAB-Reimschema, welche Zeilen reimen miteinander?", options: ["1+2, 3+4", "1+3, 2+4", "1+4, 2+3", "Alle Zeilen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p5", topicId: 26, prompt: "Was ist Assonanz (assonance)?", options: ["Wiederholung von Konsonanten", "Wiederholung von Vokallauten", "Reimende Zeilenenden", "Eine Metapher im Gedicht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p6", topicId: 26, prompt: "Was ist ein 'couplet' in der englischen Lyrik?", options: ["Ein einzelner Vers", "Zwei aufeinander folgende reimende Zeilen", "Eine vierzeilige Strophe", "Das Ende des Gedichts"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p7", topicId: 26, prompt: "Was ist ein Sonett (sonnet)?", options: ["Ein Gedicht mit 10 Zeilen", "Ein Gedicht mit 14 Zeilen", "Ein Gedicht ohne Reim", "Ein sehr langes Gedicht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p8", topicId: 26, prompt: "Was ist 'free verse' in der Lyrik?", options: ["Gedichte mit strengem Reimschema", "Gedichte ohne festes Reimschema oder Metrum", "Sehr kurze Gedichte", "Gedichte für Kinder"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p9", topicId: 26, prompt: "Was ist Metrum (meter) in der Lyrik?", options: ["Die Anzahl der Reime", "Das rhythmische Muster betont/unbetont", "Die Länge der Strophen", "Der Titel des Gedichts"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_p10", topicId: 26, prompt: "Was beschreibt das AABB-Reimschema?", options: ["Zeile 1+3 reimen, 2+4 reimen", "Zeile 1+2 reimen, 3+4 reimen", "Keine Zeilen reimen", "Alle Zeilen reimen gleich"], correctIndex: 1)
    ],
    27: [
        MathExamQuestion(id: "de_teach_27_p1", topicId: 27, prompt: "Wofür steht das Akronym FANBOYS?", options: ["For, And, Nor, But, Or, Yet, So", "First, After, Next, Before, Or, Yet, So", "For, Also, Nor, Because, Or, Yes, Since", "Few, And, Not, But, Only, Yes, Some"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_27_p2", topicId: 27, prompt: "Welche Konjunktion passt? 'I wanted to go, ___ it was raining.'", options: ["and", "but", "or", "so"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_p3", topicId: 27, prompt: "Was kommt vor einer FANBOYS-Konjunktion, die zwei Hauptsätze verbindet?", options: ["Nichts", "Ein Komma", "Ein Semikolon", "Ein Doppelpunkt"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_p4", topicId: 27, prompt: "Welche Konjunktion passt? 'She studied hard, ___ she passed the test.'", options: ["but", "nor", "so", "yet"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_p5", topicId: 27, prompt: "Was bedeutet 'nor' auf Deutsch?", options: ["oder", "aber", "weder...noch", "denn"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_p6", topicId: 27, prompt: "Welche Konjunktion passt? 'You can have cake ___ ice cream.'", options: ["but", "so", "or", "nor"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_p7", topicId: 27, prompt: "Was bedeutet 'yet' als Konjunktion auf Deutsch?", options: ["und", "denn", "aber/dennoch", "oder"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_p8", topicId: 27, prompt: "Welche Konjunktion passt? 'He was tired, ___ he kept working.'", options: ["so", "for", "yet", "and"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_p9", topicId: 27, prompt: "Was ist ein 'compound sentence' auf Englisch?", options: ["Ein Satz mit einem Hauptsatz", "Zwei Hauptsätze durch FANBOYS verbunden", "Ein Satz mit Nebensatz", "Ein kurzer Satz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_p10", topicId: 27, prompt: "Welche Konjunktion passt? 'I like cats, ___ my sister prefers dogs.'", options: ["so", "for", "yet", "and"], correctIndex: 3)
    ],
    28: [
        MathExamQuestion(id: "de_teach_28_p1", topicId: 28, prompt: "Welcher Satz ist im Aktiv?", options: ["The cake was eaten by Tom.", "The ball was kicked.", "The dog chased the cat.", "The letter was written."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_28_p2", topicId: 28, prompt: "Welcher Satz ist im Passiv?", options: ["She wrote a letter.", "The letter was written by her.", "He reads books.", "They play football."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p3", topicId: 28, prompt: "Was ist das Hilfszeitwort im englischen Passiv?", options: ["have", "do", "be (is/was/were)", "will"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_28_p4", topicId: 28, prompt: "Wie lautet dieser Satz im Passiv? 'The chef cooked the meal.'", options: ["The meal cooked the chef.", "The meal was cooked by the chef.", "The chef was cooked by the meal.", "Cooked the meal the chef."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p5", topicId: 28, prompt: "Wann verwendet man häufig das Passiv?", options: ["Wenn der Handelnde wichtig ist", "Wenn der Handelnde unbekannt oder unwichtig ist", "Immer in der Vergangenheit", "Nur in Gedichten"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p6", topicId: 28, prompt: "Wie lautet dieser Satz im Aktiv? 'The window was broken by the boy.'", options: ["The window broke the boy.", "The boy broke the window.", "The broken window was the boy.", "By the boy the window was broken."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p7", topicId: 28, prompt: "Welcher Satz ist im Passiv Präsens?", options: ["She is reading a book.", "The book is being read by her.", "She reads the book.", "She has read the book."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p8", topicId: 28, prompt: "Was bedeutet 'by' im englischen Passiv?", options: ["für", "von/durch (zeigt den Handelnden)", "mit", "ohne"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p9", topicId: 28, prompt: "Welcher Satz klingt formeller?", options: ["They make cars here.", "Cars are made here.", "We make cars here.", "Someone makes cars here."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_p10", topicId: 28, prompt: "Wie lautet dieser Satz im Passiv? 'Scientists discovered a new planet.'", options: ["A new planet discovered scientists.", "A new planet was discovered by scientists.", "Scientists were discovered by a new planet.", "The planet discovers scientists."], correctIndex: 1)
    ],
    29: [
        MathExamQuestion(id: "de_teach_29_p1", topicId: 29, prompt: "Was ist eine These (thesis statement)?", options: ["Ein Fragebogen", "Die Hauptbehauptung eines Textes", "Ein abschließender Satz", "Ein Zitat"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_p2", topicId: 29, prompt: "Was ist 'Logos' als rhetorisches Mittel?", options: ["Emotionale Appelle", "Vertrauenswürdigkeit des Autors", "Logische Argumente und Fakten", "Persönliche Erfahrungen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_29_p3", topicId: 29, prompt: "Was ist 'Pathos' als rhetorisches Mittel?", options: ["Logische Argumente", "Appell an Gefühle und Emotionen", "Fachwissen des Autors", "Statistiken und Fakten"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_p4", topicId: 29, prompt: "Was ist 'Ethos' als rhetorisches Mittel?", options: ["Emotionaler Appell", "Logische Argumente", "Glaubwürdigkeit und Vertrauen", "Übertreibungen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_29_p5", topicId: 29, prompt: "Was ist ein 'call to action' in einem überzeugenden Text?", options: ["Die Einleitung", "Eine Aufforderung, etwas zu tun", "Ein Zitat", "Eine Definition"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_p6", topicId: 29, prompt: "Was macht eine These stark?", options: ["Sie ist sehr lang", "Sie ist klar, präzise und argumentierbar", "Sie stellt eine Frage", "Sie enthält viele Adjektive"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_p7", topicId: 29, prompt: "Ein Arzt empfiehlt ein Produkt. Welches Mittel wird verwendet?", options: ["Pathos", "Logos", "Ethos", "Hyperbel"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_29_p8", topicId: 29, prompt: "Eine Werbung zeigt weinende Kinder. Welches Mittel wird verwendet?", options: ["Logos", "Ethos", "Pathos", "Statistik"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_29_p9", topicId: 29, prompt: "Was sind 'counter-arguments' im überzeugenden Schreiben?", options: ["Unterstützende Argumente", "Gegenargumente, die man widerlegen muss", "Einleitungssätze", "Schlussfolgerungen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_p10", topicId: 29, prompt: "Wo steht die These normalerweise in einem Aufsatz?", options: ["Im letzten Absatz", "In der Einleitung", "In der Mitte", "In jedem Absatz"], correctIndex: 1)
    ],
    30: [
        MathExamQuestion(id: "de_teach_30_p1", topicId: 30, prompt: "Was ist Vorausdeutung (foreshadowing)?", options: ["Das Ende der Geschichte", "Hinweise auf spätere Ereignisse", "Ein Rückblick", "Die Hauptidee"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p2", topicId: 30, prompt: "Was ist verbale Ironie (verbal irony)?", options: ["Das Gegenteil von dem, was man meint", "Eine direkte Aussage", "Eine Übertreibung", "Ein Vergleich"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_30_p3", topicId: 30, prompt: "Was ist Symbolismus (symbolism) in der Literatur?", options: ["Ein Wort wird buchstäblich verwendet", "Ein Objekt steht für eine tiefere Bedeutung", "Eine Übertreibung", "Ein Reimschema"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p4", topicId: 30, prompt: "Was ist das Thema (theme) einer Geschichte?", options: ["Der Titel", "Die Hauptbotschaft oder Erkenntnis", "Der Hauptcharakter", "Der Schauplatz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p5", topicId: 30, prompt: "Was ist ein Motiv (motif) in der Literatur?", options: ["Ein einmaliges Element", "Ein wiederkehrendes Element mit Bedeutung", "Der Konflikt", "Die Auflösung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p6", topicId: 30, prompt: "Was ist situative Ironie (situational irony)?", options: ["Man sagt das Gegenteil", "Das Gegenteil von dem passiert, was erwartet wird", "Eine Übertreibung", "Ein Vergleich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p7", topicId: 30, prompt: "Eine weiße Taube symbolisiert oft was auf Englisch?", options: ["Krieg", "Trauer", "Peace (Frieden)", "Kraft"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_30_p8", topicId: 30, prompt: "Was ist dramatische Ironie (dramatic irony)?", options: ["Der Leser weiß mehr als die Charaktere", "Ein Charakter sagt das Gegenteil", "Das Unerwartete passiert", "Eine lustige Situation"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_30_p9", topicId: 30, prompt: "Was ist ein Thema (theme) NICHT?", options: ["Eine universelle Botschaft", "Die Handlung der Geschichte", "Eine Erkenntnis über das Leben", "Etwas, das sich durch die Geschichte zieht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_p10", topicId: 30, prompt: "Ein Charakter trägt immer eine rote Rose. Was ist das?", options: ["Ironie", "Motiv", "Vorausdeutung", "Klimax"], correctIndex: 1)
    ],
    31: [
        MathExamQuestion(id: "de_teach_31_p1", topicId: 31, prompt: "Was sind die drei Hauptziele eines Autors auf Englisch?", options: ["Lesen, Schreiben, Rechnen", "To inform, to persuade, to entertain", "To describe, to explain, to question", "To argue, to define, to compare"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_p2", topicId: 31, prompt: "Ein Schulbuch erklärt Fakten. Was ist die Autorenabsicht?", options: ["To entertain", "To persuade", "To inform", "To argue"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_31_p3", topicId: 31, prompt: "Ein Roman mit spannender Handlung. Was ist die Autorenabsicht?", options: ["To inform", "To persuade", "To entertain", "To instruct"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_31_p4", topicId: 31, prompt: "Eine Werbung überzeugt dich, ein Produkt zu kaufen. Was ist die Absicht?", options: ["To inform", "To entertain", "To persuade", "To compare"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_31_p5", topicId: 31, prompt: "Was ist Bias (Voreingenommenheit) in einem Text?", options: ["Eine objektive Meinung", "Eine einseitige, parteiische Darstellung", "Eine Zusammenfassung", "Eine Definition"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_p6", topicId: 31, prompt: "Wie erkennst du Bias in einem Text?", options: ["Durch die Textlänge", "Durch einseitige Aussagen und fehlende Gegenargumente", "Durch den Titel", "Durch die Schriftgröße"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_p7", topicId: 31, prompt: "Was ist ein 'editorial' in einer Zeitung?", options: ["Ein Nachrichtenartikel", "Ein Meinungsartikel des Autors", "Ein Sportbericht", "Eine Anzeige"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_p8", topicId: 31, prompt: "Ein Kochbuch zeigt Rezepte. Was ist die Autorenabsicht?", options: ["To entertain", "To persuade", "To inform / instruct", "To compare"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_31_p9", topicId: 31, prompt: "Was bedeutet 'point of view' des Autors?", options: ["Die Erzählperspektive", "Die persönliche Meinung/Haltung des Autors", "Der Schauplatz", "Das Thema"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_p10", topicId: 31, prompt: "Ein Text zeigt nur die positiven Seiten eines Themas. Was ist das ein Zeichen für?", options: ["Objektivität", "Bias / Voreingenommenheit", "Gute Recherche", "Vollständige Darstellung"], correctIndex: 1)
    ],
    32: [
        MathExamQuestion(id: "de_teach_32_p1", topicId: 32, prompt: "Was ist Paraphrasieren (paraphrasing)?", options: ["Wörtliches Abschreiben", "Eine Idee in eigenen Worten wiedergeben", "Eine Quelle erfinden", "Ein Zitat kürzen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p2", topicId: 32, prompt: "Was ist Plagiat (plagiarism)?", options: ["Eigene Ideen schreiben", "Die Arbeit anderer als eigene ausgeben", "Ein Buch lesen", "Eine Quelle zitieren"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p3", topicId: 32, prompt: "Was sind Anführungszeichen beim direkten Zitat auf Englisch?", options: ["( )", "[ ]", "\" \"", "< >"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_32_p4", topicId: 32, prompt: "Was steht in einem MLA-Zitat zuerst?", options: ["Titel", "Erscheinungsjahr", "Nachname des Autors", "Verlag"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_32_p5", topicId: 32, prompt: "Was ist eine 'Works Cited' Seite?", options: ["Eine Inhaltsangabe", "Eine Liste aller verwendeten Quellen", "Ein Glossar", "Ein Index"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p6", topicId: 32, prompt: "Was ist der Unterschied zwischen Zitat und Paraphrase?", options: ["Kein Unterschied", "Zitat ist wörtlich, Paraphrase in eigenen Worten", "Paraphrase ist wörtlich, Zitat in eigenen Worten", "Beide sind wörtlich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p7", topicId: 32, prompt: "Was ist eine primäre Quelle (primary source)?", options: ["Ein Lehrbuch", "Eine Originalquelle wie Tagebuch oder Interview", "Ein Lexikon", "Eine Zusammenfassung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p8", topicId: 32, prompt: "Was ist eine sekundäre Quelle (secondary source)?", options: ["Ein Originaltext", "Eine Analyse oder Interpretation einer primären Quelle", "Ein persönliches Tagebuch", "Ein Interview"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p9", topicId: 32, prompt: "Warum muss man Quellen angeben?", options: ["Es ist nicht nötig", "Um Plagiat zu vermeiden und Autoren zu würdigen", "Nur bei längeren Texten", "Nur in der Schule"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_p10", topicId: 32, prompt: "Was ist ein 'in-text citation' (Quellenangabe im Text)?", options: ["Eine Fußnote", "Ein kurzer Hinweis auf die Quelle im Text selbst", "Die komplette Bibliographie", "Ein Zitat in Anführungszeichen"], correctIndex: 1)
    ],
    33: [
        MathExamQuestion(id: "de_teach_33_p1", topicId: 33, prompt: "Was ist jambischer Pentameter (iambic pentameter)?", options: ["10 Zeilen pro Strophe", "5 Jamben (unbetont/betont) pro Zeile", "Freier Vers ohne Metrum", "Ein Reimschema"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p2", topicId: 33, prompt: "Was ist ein Sonett (sonnet)?", options: ["Ein Gedicht mit 12 Zeilen", "Ein Gedicht mit 14 Zeilen", "Ein freies Gedicht", "Ein Reimgedicht mit 10 Zeilen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p3", topicId: 33, prompt: "Was unterscheidet eine Tragödie von einer Komödie bei Shakespeare?", options: ["Tragödie endet glücklich, Komödie traurig", "Tragödie endet mit Tod/Unglück, Komödie glücklich", "Kein Unterschied", "Komödien sind länger"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p4", topicId: 33, prompt: "Was ist ein Monolog/Soliloquy bei Shakespeare?", options: ["Ein Dialog zwischen zwei Charakteren", "Eine Rede, die ein Charakter allein hält", "Ein Lied im Stück", "Eine Regieanweisung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p5", topicId: 33, prompt: "Welches Stück ist eine Tragödie von Shakespeare?", options: ["A Midsummer Night's Dream", "Much Ado About Nothing", "Romeo and Juliet", "The Tempest"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_33_p6", topicId: 33, prompt: "Was ist 'thou' im elisabethanischen Englisch?", options: ["Er/sie", "Ihr/Sie (formell)", "Du (du/dir)", "Wir"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_33_p7", topicId: 33, prompt: "Was ist das Shakespeare'sche Sonett-Reimschema?", options: ["AABB CCDD EEFF GG", "ABAB CDCD EFEF GG", "ABBA CDDC EFFE GG", "AAAA BBBB CCCC DD"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p8", topicId: 33, prompt: "Was ist eine 'foil character' in der Literatur?", options: ["Der Hauptcharakter", "Ein Charakter, der den Hauptcharakter durch Kontrast hervorhebt", "Der Antagonist", "Ein Nebencharakter ohne Bedeutung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p9", topicId: 33, prompt: "Was ist der 'tragic flaw' (hamartia) eines Shakespeareschen Helden?", options: ["Seine Stärke", "Sein fataler Fehler oder seine Schwäche", "Seine Freunde", "Seine Waffe"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_p10", topicId: 33, prompt: "Was bedeutet 'doth' im elisabethanischen Englisch?", options: ["hat", "tut/macht (does)", "wird", "ist"], correctIndex: 1)
    ],
    34: [
        MathExamQuestion(id: "de_teach_34_p1", topicId: 34, prompt: "Was bedeutet die Wurzel 'bio'?", options: ["Erde", "Wasser", "Leben", "Licht"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_p2", topicId: 34, prompt: "Was bedeutet die Wurzel 'geo'?", options: ["Himmel", "Erde/Boden", "Wasser", "Feuer"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p3", topicId: 34, prompt: "Was bedeutet die Wurzel 'port'?", options: ["Hafen", "tragen/bringen", "bauen", "sehen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p4", topicId: 34, prompt: "Was bedeutet die Wurzel 'dict'?", options: ["schreiben", "sagen/sprechen", "hören", "lesen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p5", topicId: 34, prompt: "Was bedeutet die Wurzel 'scrib/script'?", options: ["lesen", "zählen", "schreiben", "sprechen"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_p6", topicId: 34, prompt: "Was bedeutet die Wurzel 'aud'?", options: ["sehen", "hören", "sprechen", "schreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p7", topicId: 34, prompt: "Was bedeutet die Wurzel 'vis/vid'?", options: ["hören", "sehen", "denken", "fühlen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p8", topicId: 34, prompt: "Was bedeutet die Wurzel 'chron'?", options: ["Zeit", "Farbe", "Zahl", "Größe"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_34_p9", topicId: 34, prompt: "Was bedeutet die Wurzel 'graph'?", options: ["malen", "schreiben/zeichnen", "singen", "bauen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_p10", topicId: 34, prompt: "Was bedeutet die Wurzel 'phon'?", options: ["Licht", "Wasser", "Klang/Ton", "Feuer"], correctIndex: 2)
    ],
    35: [
        MathExamQuestion(id: "de_teach_35_p1", topicId: 35, prompt: "Wann verwendet man ein Semikolon (;) auf Englisch?", options: ["Nach einer Einleitung", "Um zwei verwandte Hauptsätze zu verbinden", "Vor einer Liste", "Am Satzende"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p2", topicId: 35, prompt: "Wann verwendet man einen Doppelpunkt (:) auf Englisch?", options: ["Um zwei Hauptsätze zu verbinden", "Vor einer Liste oder Erklärung", "Statt eines Kommas", "Am Satzende"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p3", topicId: 35, prompt: "Was ist ein 'dangling modifier'?", options: ["Ein Adjektiv ohne Nomen", "Ein Satzteil, dessen Bezugswort unklar oder falsch ist", "Ein Verb ohne Subjekt", "Ein Komma-Fehler"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p4", topicId: 35, prompt: "Was ist Parallelismus (parallel structure)?", options: ["Zwei Hauptsätze verbinden", "Gleiche grammatische Formen in einer Reihe", "Ein Satz ohne Komma", "Ein Satz mit Semikolon"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p5", topicId: 35, prompt: "Welcher Satz zeigt korrekten Parallelismus?", options: ["She likes singing, to dance, and runs.", "She likes singing, dancing, and running.", "She likes to sing, dancing, and run.", "She likes sung, danced, and running."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p6", topicId: 35, prompt: "Was ist ein Em-Dash ( - ) auf Englisch?", options: ["Ein kurzer Bindestrich", "Ein langer Gedankenstrich für Betonung oder Einschub", "Ein Semikolon", "Ein Auslassungszeichen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p7", topicId: 35, prompt: "Welcher Satz verwendet ein Semikolon korrekt?", options: ["I love English; and German.", "I love English; it opens doors.", "I love; English.", "I; love English."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p8", topicId: 35, prompt: "Was ist ein 'run-on sentence'?", options: ["Ein sehr kurzer Satz", "Zwei Hauptsätze ohne korrekte Interpunktion verbunden", "Ein Satz mit vielen Adjektiven", "Ein Satz im Passiv"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p9", topicId: 35, prompt: "Welcher Satz verwendet einen Doppelpunkt korrekt?", options: ["I need: a pen.", "I need the following: a pen, paper, and ruler.", "I: need a pen.", "I need a pen: to write."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_p10", topicId: 35, prompt: "Was ist ein 'comma splice'?", options: ["Ein Komma nach einer Einleitung", "Zwei Hauptsätze nur durch ein Komma verbunden (falsch)", "Ein Komma vor 'and'", "Ein Komma in einer Liste"], correctIndex: 1)
    ]
]

let deTeachingExamB: [Int: [MathExamQuestion]] = [
    19: [
        MathExamQuestion(id: "de_teach_19_e1", topicId: 19, prompt: "Was ist das Subjekt in 'Every summer, the children swim in the lake'?", options: ["Every summer", "swim", "the lake", "the children"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_19_e2", topicId: 19, prompt: "Welcher Satz hat ein zusammengesetztes Prädikat?", options: ["Tom and Lisa run.", "She sings and dances.", "The big dog barks.", "We eat lunch."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_e3", topicId: 19, prompt: "Was fehlt in diesem Satz? 'Slowly walked home.'", options: ["Ein Prädikat", "Ein Subjekt", "Ein Objekt", "Ein Adjektiv"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_e4", topicId: 19, prompt: "Was ist das Prädikat in 'The excited crowd cheered loudly'?", options: ["The excited crowd", "cheered loudly", "excited", "The crowd"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_e5", topicId: 19, prompt: "Welcher Satz ist ein vollständiger Satz (complete sentence)?", options: ["Because it was raining.", "The tall trees in the forest.", "She finished her homework.", "Running very quickly."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_e6", topicId: 19, prompt: "Was ist das Subjekt in 'There are many stars in the sky'?", options: ["There", "many stars", "the sky", "stars"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_e7", topicId: 19, prompt: "Welche Aussage über Subjekte ist FALSCH?", options: ["Das Subjekt führt die Handlung aus", "Das Subjekt ist immer ein Nomen oder Pronomen", "Das Subjekt steht immer nach dem Verb", "Das Subjekt kann ein Name sein"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_e8", topicId: 19, prompt: "Was ist ein 'sentence fragment'?", options: ["Ein vollständiger Satz", "Ein Satzteil ohne Subjekt oder Prädikat", "Ein langer Satz", "Ein Satz mit zwei Subjekten"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_19_e9", topicId: 19, prompt: "Was ist das Subjekt in 'It is raining outside'?", options: ["raining", "outside", "It", "is"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_19_e10", topicId: 19, prompt: "Welcher Satz enthält ein indirektes Objekt?", options: ["She runs fast.", "He gave her a gift.", "The dog barks.", "They play football."], correctIndex: 1)
    ],
    20: [
        MathExamQuestion(id: "de_teach_20_e1", topicId: 20, prompt: "Welche Art von Stilmittel ist 'The classroom was a zoo'?", options: ["Simile", "Metapher", "Personifikation", "Hyperbel"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_e2", topicId: 20, prompt: "Welche Art von Stilmittel ist 'The flowers danced in the breeze'?", options: ["Hyperbel", "Simile", "Metapher", "Personifikation"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_20_e3", topicId: 20, prompt: "Welche Art von Stilmittel ist 'I've waited forever for this'?", options: ["Metapher", "Personifikation", "Hyperbel", "Simile"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_20_e4", topicId: 20, prompt: "Welche Art von Stilmittel ist 'Her eyes were like stars'?", options: ["Metapher", "Simile", "Personifikation", "Ironie"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_e5", topicId: 20, prompt: "Warum verwendet ein Autor bildhafte Sprache?", options: ["Um den Text kürzer zu machen", "Um lebhafte Bilder zu erzeugen", "Um Fakten zu präsentieren", "Um formell zu schreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_e6", topicId: 20, prompt: "Welche Art von Stilmittel ist 'The old car coughed and sputtered'?", options: ["Simile", "Metapher", "Hyperbel", "Personifikation"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_20_e7", topicId: 20, prompt: "Welche Art von Stilmittel ist 'He's as stubborn as a mule'?", options: ["Metapher", "Personifikation", "Simile", "Hyperbel"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_20_e8", topicId: 20, prompt: "Welche Art von Stilmittel ist 'Life is a roller coaster'?", options: ["Simile", "Metapher", "Personifikation", "Alliteration"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_e9", topicId: 20, prompt: "Was ist Alliteration?", options: ["Reimende Zeilenenden", "Gleiche Anfangskonsonanten in aufeinanderfolgenden Wörtern", "Ein Vergleich", "Eine Übertreibung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_20_e10", topicId: 20, prompt: "Welche Art von Stilmittel ist 'Peter Piper picked a peck of pickled peppers'?", options: ["Simile", "Metapher", "Alliteration", "Hyperbel"], correctIndex: 2)
    ],
    21: [
        MathExamQuestion(id: "de_teach_21_e1", topicId: 21, prompt: "Was bedeutet 'dilapidated' in: 'The dilapidated house had broken windows and crumbling walls'?", options: ["neu und modern", "verfallen und baufällig", "groß und schön", "sauber und ordentlich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_e2", topicId: 21, prompt: "Was bedeutet 'serene' in: 'The serene lake was perfectly calm and quiet'?", options: ["stürmisch", "tief", "ruhig und friedlich", "kalt"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_e3", topicId: 21, prompt: "Welcher Kontexthinweis hilft, 'trembling' zu verstehen? 'She was trembling  -  her hands shook with fear'?", options: ["her hands shook with fear", "She was", "hands", "fear"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_21_e4", topicId: 21, prompt: "Was bedeutet 'frugal' in: 'He was frugal  -  never spent more than he had to'?", options: ["großzügig", "sparsam", "reich", "ängstlich"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_e5", topicId: 21, prompt: "Was bedeutet 'vivid' in: 'She painted a vivid picture with bright, striking colors'?", options: ["blass", "einfach", "lebhaft und eindrucksvoll", "schwarz-weiß"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_e6", topicId: 21, prompt: "Was bedeutet 'meticulous' in: 'He was meticulous, checking every detail twice'?", options: ["nachlässig", "schnell", "sehr sorgfältig", "vergesslich"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_e7", topicId: 21, prompt: "Was bedeutet 'perplexed' in: 'She was perplexed  -  the puzzle made no sense to her'?", options: ["glücklich", "verwirrt", "gelangweilt", "wütend"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_e8", topicId: 21, prompt: "Was bedeutet 'abundant' in: 'The forest had abundant wildlife  -  animals everywhere'?", options: ["selten", "gefährlich", "reichlich vorhanden", "verschwunden"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_21_e9", topicId: 21, prompt: "Was bedeutet 'elated' in: 'She was elated when she won first prize  -  jumping for joy'?", options: ["enttäuscht", "überglücklich", "überrascht", "traurig"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_21_e10", topicId: 21, prompt: "Welche Strategie hilft bei unbekannten Wörtern NICHT?", options: ["Den Kontext lesen", "Präfixe/Suffixe analysieren", "Das Wort ignorieren", "Synonyme im Text suchen"], correctIndex: 2)
    ],
    22: [
        MathExamQuestion(id: "de_teach_22_e1", topicId: 22, prompt: "Was ist die Hauptidee in: 'Exercise is important. It keeps your heart healthy, builds muscles, and improves mood.'?", options: ["Exercise builds muscles.", "Exercise improves mood.", "Exercise is important for health.", "Exercise makes you tired."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_22_e2", topicId: 22, prompt: "Welcher Satz ist ein stützendes Detail (supporting detail), kein Hauptidee-Satz?", options: ["Dogs make great pets.", "A dog named Rex barked at strangers.", "Dogs are loyal companions.", "Dogs are popular worldwide."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e3", topicId: 22, prompt: "Was ist die implizite Hauptidee (implied main idea)?", options: ["Eine direkt ausgesprochene Hauptidee", "Eine Hauptidee, die nicht explizit genannt wird", "Das Thema des Textes", "Der erste Satz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e4", topicId: 22, prompt: "Wie unterscheidet man Hauptidee von Thema?", options: ["Kein Unterschied", "Thema ist ein Wort/Phrase, Hauptidee ist ein vollständiger Satz", "Hauptidee ist kürzer", "Thema ist immer explizit"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e5", topicId: 22, prompt: "Was ist der Zweck stützender Details?", options: ["Die Hauptidee ersetzen", "Die Hauptidee beweisen oder erklären", "Den Text verlängern", "Den Leser ablenken"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e6", topicId: 22, prompt: "Was ist die Hauptidee in: 'Rainforests are disappearing. Logging, farming, and mining destroy them daily.'?", options: ["Mining destroys rainforests.", "Rainforests are being destroyed.", "Logging is bad.", "Farming uses land."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e7", topicId: 22, prompt: "Was macht eine gute Topic Sentence aus?", options: ["Sie enthält viele Details", "Sie führt die Hauptidee klar ein", "Sie beendet den Absatz", "Sie stellt eine Frage"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e8", topicId: 22, prompt: "Welches ist ein irrelevantes Detail für: 'Dogs make great pets'?", options: ["Dogs are loyal.", "Dogs love their owners.", "Cats are also popular pets.", "Dogs can learn commands."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_22_e9", topicId: 22, prompt: "Was ist ein 'summary' auf Deutsch?", options: ["Eine Analyse", "Eine Zusammenfassung der Hauptideen", "Eine persönliche Meinung", "Ein Zitat"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_22_e10", topicId: 22, prompt: "Wie viele Hauptideen hat ein gut geschriebener Absatz normalerweise?", options: ["Keine", "Eine", "Drei", "Unbegrenzt viele"], correctIndex: 1)
    ],
    23: [
        MathExamQuestion(id: "de_teach_23_e1", topicId: 23, prompt: "Aus welcher Perspektive ist: 'I remember the day we moved to a new city'?", options: ["Zweite Person", "Dritte Person begrenzt", "Erste Person", "Allwissend"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_e2", topicId: 23, prompt: "Aus welcher Perspektive ist: 'You open the door and gasp in surprise'?", options: ["Erste Person", "Zweite Person", "Dritte Person", "Allwissend"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e3", topicId: 23, prompt: "Was ist die dritte Person begrenzt (third person limited)?", options: ["Erzähler kennt alle Gedanken", "Erzähler kennt nur die Gedanken eines Charakters", "Erzähler ist ein Charakter in der Geschichte", "Erzähler kennt keine Gedanken"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e4", topicId: 23, prompt: "Was ist die dritte Person allwissend (third person omniscient)?", options: ["Erzähler ist ein Charakter", "Erzähler kennt die Gedanken aller Charaktere", "Erzähler kennt nur eine Perspektive", "Erzähler spricht den Leser an"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e5", topicId: 23, prompt: "Welcher Vorteil hat die Ich-Perspektive (first person)?", options: ["Wir kennen alle Charaktere gut", "Sehr persönlich, wir kennen den Erzähler gut", "Objektivere Darstellung", "Mehr Charaktere werden beschrieben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e6", topicId: 23, prompt: "Aus welcher Perspektive ist: 'He knew she was lying, but said nothing'?", options: ["Erste Person", "Zweite Person", "Dritte Person begrenzt", "Dritte Person allwissend"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_23_e7", topicId: 23, prompt: "Was ist ein 'unreliable narrator'?", options: ["Ein Erzähler mit vollem Wissen", "Ein Erzähler, dem man nicht vertrauen kann", "Ein allwissender Erzähler", "Ein Erzähler in zweiter Person"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e8", topicId: 23, prompt: "Warum wechseln Autoren manchmal die Perspektive?", options: ["Aus Versehen", "Um verschiedene Sichtweisen zu zeigen", "Weil es einfacher ist", "Um den Leser zu verwirren"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_23_e9", topicId: 23, prompt: "Aus welcher Perspektive ist: 'We must fight for our future'?", options: ["Erste Person Singular", "Zweite Person", "Erste Person Plural", "Dritte Person"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_23_e10", topicId: 23, prompt: "Welcher Nachteil hat die Ich-Perspektive?", options: ["Zu formell", "Begrenzte Sichtweise  -  nur eine Perspektive", "Zu viele Charaktere", "Zu objektiv"], correctIndex: 1)
    ],
    24: [
        MathExamQuestion(id: "de_teach_24_e1", topicId: 24, prompt: "Welche Textstruktur liegt vor? 'Cats are independent; dogs are loyal and need more attention.'", options: ["Zeitfolge", "Ursache/Wirkung", "Vergleich/Kontrast", "Problem/Lösung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_e2", topicId: 24, prompt: "Welche Textstruktur liegt vor? 'First wash the vegetables, then cut them, finally cook them.'", options: ["Vergleich", "Ursache/Wirkung", "Problem/Lösung", "Chronologisch"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_24_e3", topicId: 24, prompt: "Welche Textstruktur liegt vor? 'Air pollution is rising. As a result, more people have asthma.'", options: ["Zeitfolge", "Ursache/Wirkung", "Vergleich", "Beschreibung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_e4", topicId: 24, prompt: "Welches Signalwort zeigt Kontrast an?", options: ["similarly", "therefore", "however", "because"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_e5", topicId: 24, prompt: "Welche Textstruktur liegt vor? 'Many students struggle with reading. Schools should offer extra support.'", options: ["Zeitfolge", "Vergleich", "Problem/Lösung", "Ursache/Wirkung"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_e6", topicId: 24, prompt: "Was bedeutet 'consequently' auf Deutsch?", options: ["obwohl", "zum Beispiel", "infolgedessen", "zunächst"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_e7", topicId: 24, prompt: "Welche Textstruktur eignet sich für einen Reisebericht?", options: ["Problem/Lösung", "Chronologisch/Zeitfolge", "Vergleich/Kontrast", "Ursache/Wirkung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_e8", topicId: 24, prompt: "Welches Signalwort zeigt Ähnlichkeit an?", options: ["but", "however", "similarly", "although"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_24_e9", topicId: 24, prompt: "Was bedeutet 'although' auf Deutsch?", options: ["deshalb", "obwohl", "zuerst", "danach"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_24_e10", topicId: 24, prompt: "Kann ein Text mehrere Strukturen gleichzeitig haben?", options: ["Nein, immer nur eine", "Ja, Texte können mehrere Strukturen mischen", "Nur in wissenschaftlichen Texten", "Nur in Kurzgeschichten"], correctIndex: 1)
    ],
    25: [
        MathExamQuestion(id: "de_teach_25_e1", topicId: 25, prompt: "Was ist der 'narrative arc' (Handlungsbogen)?", options: ["Das Reimschema", "Der Spannungsaufbau: Einführung → Höhepunkt → Auflösung", "Die Charakterentwicklung", "Die Erzählperspektive"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e2", topicId: 25, prompt: "Was ist die 'rising action' in einer Geschichte?", options: ["Die Einführung der Charaktere", "Ereignisse, die zur Hauptspannung führen", "Der Höhepunkt", "Die Auflösung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e3", topicId: 25, prompt: "Was ist die 'falling action'?", options: ["Ereignisse nach dem Höhepunkt zur Auflösung", "Der Beginn der Geschichte", "Der Konflikt", "Die Einführung"], correctIndex: 0),
        MathExamQuestion(id: "de_teach_25_e4", topicId: 25, prompt: "Welcher Dialog ist korrekt interpunktiert?", options: ["\"Come here\" said Tom.", "\"Come here,\" said Tom.", "\"Come here\", said Tom", "Come here, said Tom."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e5", topicId: 25, prompt: "Was macht Charakterentwicklung (character development) aus?", options: ["Der Charakter bleibt gleich", "Der Charakter verändert sich durch Ereignisse", "Der Charakter stirbt am Ende", "Der Charakter ist der Antagonist"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e6", topicId: 25, prompt: "Was ist ein 'protagonist'?", options: ["Der Bösewicht", "Die Hauptfigur/der Held", "Der Erzähler", "Ein Nebencharakter"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e7", topicId: 25, prompt: "Was ist ein 'antagonist'?", options: ["Der Held", "Der Erzähler", "Die Kraft/Person, die dem Protagonisten entgegenwirkt", "Der beste Freund"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_25_e8", topicId: 25, prompt: "Was ist 'exposition' in einer Geschichte?", options: ["Der Höhepunkt", "Die Einführung von Charakteren, Schauplatz und Grundsituation", "Die Auflösung", "Der Konflikt"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e9", topicId: 25, prompt: "Was ist 'show don't tell' beim Schreiben?", options: ["Direkt sagen, was passiert", "Durch Details und Handlungen zeigen, statt direkt zu sagen", "Kurz und einfach schreiben", "Viele Adjektive benutzen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_25_e10", topicId: 25, prompt: "Was ist der Unterschied zwischen internem und externem Konflikt?", options: ["Kein Unterschied", "Intern: Kampf im Inneren des Charakters; Extern: Kampf mit Außenwelt", "Intern: mit anderen Charakteren; Extern: mit sich selbst", "Intern ist wichtiger"], correctIndex: 1)
    ],
    26: [
        MathExamQuestion(id: "de_teach_26_e1", topicId: 26, prompt: "Was ist das Reimschema von: rose/goes/shows/knows?", options: ["ABAB", "AABB", "ABBA", "AAAA"], correctIndex: 3),
        MathExamQuestion(id: "de_teach_26_e2", topicId: 26, prompt: "Was ist jambischer Pentameter (iambic pentameter)?", options: ["5 betonte Silben pro Zeile", "Abwechselnd un-/betonte Silben, 10 pro Zeile", "Freier Vers", "4 Jamben pro Zeile"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e3", topicId: 26, prompt: "Was ist ein Haiku?", options: ["Ein 14-zeiliges Gedicht", "Ein japanisches Gedicht: 5-7-5 Silben", "Ein Liebesgedicht", "Ein Gedicht ohne Reim"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e4", topicId: 26, prompt: "Was ist Onomatopoeia auf Englisch?", options: ["Ein Reimschema", "Wörter, die Geräusche imitieren (buzz, crash, bang)", "Eine Art Metapher", "Ein Typ Strophe"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e5", topicId: 26, prompt: "Was ist ein 'quatrain'?", options: ["Eine zweizeilige Strophe", "Eine vierzeilige Strophe", "Eine achtzeilige Strophe", "Eine einzeilige Strophe"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e6", topicId: 26, prompt: "Was ist 'enjambment' in der Lyrik?", options: ["Ein Reimschema", "Ein Satz läuft über das Zeilenende hinaus", "Eine kurze Pause am Zeilenende", "Ein Gedicht ohne Strophen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e7", topicId: 26, prompt: "Was ist ein 'couplet' am Ende eines Shakespeareschen Sonetts?", options: ["Die ersten zwei Zeilen", "Zwei abschließende reimende Zeilen", "Eine vierzeilige Strophe", "Der Titel"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e8", topicId: 26, prompt: "Was ist 'caesura' in der Lyrik?", options: ["Ein Reimschema", "Eine Pause mitten in einer Zeile", "Eine Art Metapher", "Ein abruptes Ende"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e9", topicId: 26, prompt: "Was ist 'tone' (Ton) in einem Gedicht?", options: ["Das Reimschema", "Die Haltung/Stimmung des Dichters", "Die Anzahl der Silben", "Die Strophenstruktur"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_26_e10", topicId: 26, prompt: "Was ist 'mood' (Atmosphäre) in einem Gedicht?", options: ["Die Meinung des Autors", "Das Gefühl, das beim Leser entsteht", "Das Reimschema", "Der Titel"], correctIndex: 1)
    ],
    27: [
        MathExamQuestion(id: "de_teach_27_e1", topicId: 27, prompt: "Was ist der Unterschied zwischen einem einfachen und einem zusammengesetzten Satz?", options: ["Kein Unterschied", "Einfacher Satz: ein Hauptsatz; zusammengesetzt: zwei oder mehr", "Zusammengesetzter Satz ist kürzer", "Einfacher Satz hat mehr Verben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e2", topicId: 27, prompt: "Welcher ist ein zusammengesetzter Satz (compound sentence)?", options: ["She is tall.", "She is tall, and she runs fast.", "Running fast is fun.", "Because she runs fast."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e3", topicId: 27, prompt: "Was ist ein Nebensatz (subordinate clause)?", options: ["Ein vollständiger Satz", "Ein Satzteil, der nicht alleine stehen kann", "Ein Hauptsatz mit Konjunktion", "Ein Satz ohne Verb"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e4", topicId: 27, prompt: "Was ist ein 'complex sentence'?", options: ["Zwei Hauptsätze", "Ein Hauptsatz und ein Nebensatz", "Drei Hauptsätze", "Ein Satz ohne Konjunktion"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e5", topicId: 27, prompt: "Was sind unterordnende Konjunktionen (subordinating conjunctions)?", options: ["FANBOYS", "because, although, when, if, since, unless", "and, but, or", "Pronomen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e6", topicId: 27, prompt: "Welcher Satz ist ein 'compound-complex sentence'?", options: ["She runs.", "She runs, but he walks.", "She runs fast, but he walks slowly because he is tired.", "Although she runs."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_e7", topicId: 27, prompt: "Wann kommt ein Komma vor der FANBOYS-Konjunktion?", options: ["Nie", "Immer", "Wenn sie zwei Hauptsätze verbindet", "Nur bei 'and'"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_27_e8", topicId: 27, prompt: "Was bedeutet 'for' als FANBOYS-Konjunktion?", options: ["für (Präposition)", "denn/weil (erklärt Grund)", "und", "aber"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e9", topicId: 27, prompt: "Was ist ein 'correlative conjunction'?", options: ["FANBOYS", "Paare wie 'both...and', 'either...or', 'neither...nor'", "Unterordnende Konjunktionen", "Präpositionen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_27_e10", topicId: 27, prompt: "Welcher Satz verwendet 'nor' korrekt?", options: ["She likes cats nor dogs.", "She likes neither cats nor dogs.", "She nor likes cats.", "Nor she likes cats."], correctIndex: 1)
    ],
    28: [
        MathExamQuestion(id: "de_teach_28_e1", topicId: 28, prompt: "Wie lautet 'They built the bridge in 1900' im Passiv?", options: ["The bridge built in 1900.", "The bridge was built in 1900.", "The bridge is built in 1900.", "Built the bridge in 1900."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_e2", topicId: 28, prompt: "Wie lautet 'Someone stole my wallet' im Passiv?", options: ["My wallet stole.", "My wallet was stolen.", "My wallet is stolen by someone.", "My wallet has stolen."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_e3", topicId: 28, prompt: "Wie lautet 'They are building a new school' im Passiv?", options: ["A new school is being built.", "A new school was built.", "A new school will be built.", "A new school has been built."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_28_e4", topicId: 28, prompt: "In welchem Kontext ist das Passiv BESONDERS nützlich?", options: ["In Gesprächen", "In wissenschaftlichen Texten, wo der Handelnde unwichtig ist", "In Gedichten", "In Kurzgeschichten"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_e5", topicId: 28, prompt: "Wie lautet 'The teacher will correct the tests' im Passiv?", options: ["The tests corrected by the teacher.", "The tests will be corrected by the teacher.", "The tests are corrected.", "The tests were corrected."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_e6", topicId: 28, prompt: "Was ist der 'agent' im Passiv?", options: ["Das Verb", "Die Person/Sache, die die Handlung ausführt (nach 'by')", "Das Subjekt des Passivsatzes", "Das Objekt"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_28_e7", topicId: 28, prompt: "Wie lautet 'Nobody has seen him' im Passiv?", options: ["He has not been seen.", "He was not seen.", "He is not seen.", "He will not be seen."], correctIndex: 0),
        MathExamQuestion(id: "de_teach_28_e8", topicId: 28, prompt: "Welcher Satz ist AKTIV?", options: ["The report was written by Lisa.", "Mistakes were made.", "The team won the championship.", "The window was opened."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_28_e9", topicId: 28, prompt: "Was ist die Passivform von 'have eaten'?", options: ["was eaten", "is eaten", "have been eaten", "will be eaten"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_28_e10", topicId: 28, prompt: "Warum verwendet man Passiv ohne 'by'-Phrase?", options: ["Immer falsch ohne 'by'", "Wenn der Handelnde unbekannt oder unwichtig ist", "Nur in der Vergangenheit", "Nur in formellen Texten"], correctIndex: 1)
    ],
    29: [
        MathExamQuestion(id: "de_teach_29_e1", topicId: 29, prompt: "Welche ist eine starke These für einen Aufsatz über Schuluniformen?", options: ["Schuluniformen sind ein Thema.", "Schuluniformen sollten in allen Schulen Pflicht sein.", "Manche Schulen haben Uniformen.", "Uniformen sind Kleidung."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e2", topicId: 29, prompt: "Was ist eine 'rebuttal' in einem Aufsatz?", options: ["Die These", "Die Widerlegung eines Gegenarguments", "Ein Zitat", "Die Einleitung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e3", topicId: 29, prompt: "Welches ist ein Logos-Argument?", options: ["Stell dir vor, wie glücklich du sein wirst.", "Studien zeigen, dass Bewegung die Gesundheit verbessert.", "Dr. Smith empfiehlt dieses Produkt.", "Jedes Kind verdient eine Chance."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e4", topicId: 29, prompt: "Welches ist ein Pathos-Argument?", options: ["Statistiken belegen den Rückgang.", "Der Experte empfiehlt es.", "Denke an die Kinder, die leiden.", "Logisch gesehen ist es besser."], correctIndex: 2),
        MathExamQuestion(id: "de_teach_29_e5", topicId: 29, prompt: "Was ist 'audience awareness' beim Schreiben?", options: ["Den eigenen Stil ignorieren", "Den Text für die Zielgruppe anpassen", "Immer formell schreiben", "Kurz schreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e6", topicId: 29, prompt: "Was ist eine 'concession' in einem Aufsatz?", options: ["Die These", "Das Zugeben eines Gegenarguments vor der Widerlegung", "Der Schluss", "Ein Zitat"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e7", topicId: 29, prompt: "Welche Phrasen leiten einen Gegenargument-Abschnitt ein?", options: ["For example, such as", "Some argue that, opponents claim", "First, second, finally", "Similarly, likewise"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e8", topicId: 29, prompt: "Was macht einen überzeugenden Schluss stark?", options: ["Neue Argumente einführen", "Die These wiederholen und einen Call to Action geben", "Den Text zusammenfassen ohne Meinung", "Eine Frage stellen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e9", topicId: 29, prompt: "Was ist ein 'warrant' in einem Argument?", options: ["Ein Zitat", "Die Begründung, warum das Beweismittel die These stützt", "Eine Statistik", "Ein Gegenargument"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_29_e10", topicId: 29, prompt: "Welche Aussage über eine gute These ist FALSCH?", options: ["Sie ist klar und präzise", "Sie kann nicht widerlegt werden", "Sie beantwortet eine Frage", "Sie nimmt eine klare Position ein"], correctIndex: 1)
    ],
    30: [
        MathExamQuestion(id: "de_teach_30_e1", topicId: 30, prompt: "Was ist 'cosmic irony'?", options: ["Ironie in einem Gespräch", "Das Schicksal/Universum spielt jemandem einen Streich", "Eine wörtliche Aussage", "Eine Übertreibung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e2", topicId: 30, prompt: "Was ist ein 'archetype' in der Literatur?", options: ["Ein bestimmter Charakter", "Ein universelles Symbol oder Charaktermuster", "Ein Reimschema", "Ein Handlungsort"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e3", topicId: 30, prompt: "Was ist 'allegory' in der Literatur?", options: ["Ein direkter Vergleich", "Eine Geschichte mit versteckter tieferer Bedeutung", "Eine Übertreibung", "Ein Charaktermerkmal"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e4", topicId: 30, prompt: "Welches literarische Mittel liegt vor, wenn ein Charakter seinen Tod ankündigt, ohne es zu wissen?", options: ["Ironie", "Vorausdeutung", "Dramatische Ironie", "Motiv"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_30_e5", topicId: 30, prompt: "Was ist 'pathos' als literarisches Mittel?", options: ["Logische Argumentation", "Eine Szene, die starke Emotionen hervorruft", "Ein Symbol", "Eine Metapher"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e6", topicId: 30, prompt: "Was ist ein 'red herring' in der Literatur?", options: ["Ein Symbol für Gefahr", "Ein falscher Hinweis, der den Leser ablenkt", "Ein roter Fisch als Symbol", "Ein Motiv"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e7", topicId: 30, prompt: "Was unterscheidet Thema (theme) von Handlung (plot)?", options: ["Kein Unterschied", "Handlung sind die Ereignisse; Thema die Botschaft dahinter", "Thema sind die Ereignisse", "Handlung ist die Botschaft"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e8", topicId: 30, prompt: "Was ist 'hubris' in der Tragödie?", options: ["Übermäßige Bescheidenheit", "Übermäßiger Stolz/Hochmut", "Feigheit", "Weisheit"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e9", topicId: 30, prompt: "Was ist 'catharsis' in der Tragödie?", options: ["Der Konflikt", "Emotionale Reinigung/Erleichterung beim Publikum", "Der Höhepunkt", "Der Held"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_30_e10", topicId: 30, prompt: "Was ist 'in medias res'?", options: ["Das Ende einer Geschichte", "Eine Geschichte beginnt mitten in der Handlung", "Ein Rückblick", "Die Einführung"], correctIndex: 1)
    ],
    31: [
        MathExamQuestion(id: "de_teach_31_e1", topicId: 31, prompt: "Was ist 'media literacy' auf Deutsch?", options: ["Lesen lernen", "Medien kritisch verstehen und hinterfragen", "Zeitung lesen", "Im Internet surfen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e2", topicId: 31, prompt: "Was ist ein 'loaded word'?", options: ["Ein langes Wort", "Ein Wort mit starker emotionaler Konnotation", "Ein Fremdwort", "Ein technischer Begriff"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e3", topicId: 31, prompt: "Was ist 'propaganda'?", options: ["Objektive Berichterstattung", "Parteiische Informationen zur Beeinflussung der Meinung", "Eine Literaturform", "Ein Zeitungsartikel"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e4", topicId: 31, prompt: "Was ist Satire?", options: ["Eine ernste Kritik", "Humor oder Ironie zur Kritik an Gesellschaft/Politik", "Ein Gedicht", "Eine Biographie"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e5", topicId: 31, prompt: "Was ist ein 'fact' versus eine 'opinion' auf Englisch?", options: ["Kein Unterschied", "Fakt ist beweisbar; Meinung ist eine persönliche Ansicht", "Meinung ist beweisbar", "Fakt ist eine persönliche Ansicht"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e6", topicId: 31, prompt: "Was ist 'connotation' auf Deutsch?", options: ["Wörtliche Bedeutung", "Nebenbedeutung/emotionale Assoziation", "Grammatikregel", "Aussprache"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e7", topicId: 31, prompt: "Was ist 'denotation' auf Deutsch?", options: ["Emotionale Bedeutung", "Wörtliche, direkte Bedeutung", "Bildliche Bedeutung", "Veraltete Bedeutung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e8", topicId: 31, prompt: "Was ist 'tone' in einem nicht-fiktionalen Text?", options: ["Das Thema", "Die Haltung/Einstellung des Autors zum Thema", "Die Struktur", "Das Zielpublikum"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e9", topicId: 31, prompt: "Was ist ein 'anecdote' in einem Aufsatz?", options: ["Eine Statistik", "Eine kurze persönliche Geschichte als Beispiel", "Ein Zitat", "Eine Definition"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_31_e10", topicId: 31, prompt: "Was ist 'diction' auf Deutsch?", options: ["Grammatik", "Wortwahl des Autors", "Satzlänge", "Textstruktur"], correctIndex: 1)
    ],
    32: [
        MathExamQuestion(id: "de_teach_32_e1", topicId: 32, prompt: "Was ist ein 'annotated bibliography'?", options: ["Eine Quellenliste ohne Kommentare", "Eine Quellenliste mit kurzen Erklärungen zu jeder Quelle", "Ein Index", "Eine Inhaltsangabe"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e2", topicId: 32, prompt: "Was ist 'peer review'?", options: ["Ein Selbststudium", "Überprüfung durch Fachkollegen", "Eine Lehrerkorrektur", "Ein automatischer Check"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e3", topicId: 32, prompt: "Was ist eine 'thesis-driven' Recherche?", options: ["Recherche ohne festes Ziel", "Recherche, die eine bestimmte These belegt/widerlegt", "Nur Fakten sammeln", "Online-Recherche"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e4", topicId: 32, prompt: "Was macht eine Quelle zuverlässig (reliable)?", options: ["Sie ist im Internet", "Sie ist von einem Experten verfasst und überprüft", "Sie ist kostenlos", "Sie ist sehr lang"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e5", topicId: 32, prompt: "Was ist 'synthesis' beim Schreiben?", options: ["Eine Quelle direkt kopieren", "Ideen aus mehreren Quellen kombinieren und verbinden", "Eine Quelle paraphrasieren", "Ein direktes Zitat einbauen"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e6", topicId: 32, prompt: "Was ist ein 'block quote' auf Englisch?", options: ["Ein kurzes Zitat", "Ein langes Zitat (4+ Zeilen), eingerückt ohne Anführungszeichen", "Ein indirektes Zitat", "Ein Zitat ohne Quelle"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e7", topicId: 32, prompt: "Was ist 'academic integrity'?", options: ["Nur gute Noten bekommen", "Ehrliches, eigenes Arbeiten ohne Betrug", "Viel recherchieren", "Formell schreiben"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e8", topicId: 32, prompt: "Was bedeutet 'et al.' in einem MLA-Zitat?", options: ["und so weiter", "und andere (bei mehr als einem Autor)", "zum Beispiel", "vergleiche"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e9", topicId: 32, prompt: "Was ist eine 'credible source'?", options: ["Eine populäre Website", "Eine vertrauenswürdige, überprüfte Quelle", "Eine alte Quelle", "Eine kostenlose Quelle"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_32_e10", topicId: 32, prompt: "Warum sollte man mehrere Quellen verwenden?", options: ["Es sieht besser aus", "Für eine ausgewogene, vollständige Darstellung", "Wegen der Zitatmenge", "Um die Arbeit zu verlängern"], correctIndex: 1)
    ],
    33: [
        MathExamQuestion(id: "de_teach_33_e1", topicId: 33, prompt: "Was ist die 'Globe Theatre'?", options: ["Ein modernes Theater", "Shakespeares berühmtes Theater in London", "Ein Kino", "Eine Oper"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e2", topicId: 33, prompt: "Was ist das Thema von 'Romeo and Juliet'?", options: ["Freundschaft und Treue", "Liebe und die Folgen von Familienfehden", "Macht und Verrat", "Abenteuer und Entdeckung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e3", topicId: 33, prompt: "Was ist ein 'aside' in einem Theaterstück?", options: ["Ein Dialog", "Eine Bemerkung, die nur das Publikum hört", "Ein Monolog", "Eine Regieanweisung"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e4", topicId: 33, prompt: "Was ist 'prose' im Gegensatz zu 'verse' bei Shakespeare?", options: ["Prose reimt, verse nicht", "Prose ist normale Sprache; verse ist in Metrum/Reim", "Kein Unterschied", "Verse ist moderner"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e5", topicId: 33, prompt: "Was bedeutet 'wherefore art thou' in modernem Englisch?", options: ["Wo bist du?", "Warum bist du (Romeo)?", "Wer bist du?", "Wie bist du?"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e6", topicId: 33, prompt: "Was ist ein 'tragic hero' nach Aristoteles?", options: ["Ein perfekter Held", "Ein edler Charakter mit einem fatalen Fehler", "Ein böser Charakter", "Ein komischer Charakter"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e7", topicId: 33, prompt: "Was ist 'blank verse'?", options: ["Verse ohne jede Struktur", "Verse in jambischem Pentameter ohne Endreim", "Kurze Verse", "Verse mit Endreim"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e8", topicId: 33, prompt: "Was ist eine 'folio' bei Shakespeare?", options: ["Ein einzelnes Blatt", "Eine gesammelte Ausgabe seiner Werke", "Ein Theaterprogramm", "Ein Brief"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e9", topicId: 33, prompt: "Was ist der Unterschied zwischen 'thee' und 'thou'?", options: ["Kein Unterschied", "'thou' ist Subjektform, 'thee' ist Objektform von 'du'", "'thee' ist Subjekt, 'thou' ist Objekt", "Beides bedeutet 'ihr'"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_33_e10", topicId: 33, prompt: "Was ist 'catharsis' laut Aristoteles?", options: ["Der tragische Fehler", "Emotionale Reinigung durch Mitleid und Schrecken", "Die Handlung einer Tragödie", "Der Antagonist"], correctIndex: 1)
    ],
    34: [
        MathExamQuestion(id: "de_teach_34_e1", topicId: 34, prompt: "Was bedeutet die Wurzel 'terra'?", options: ["Wasser", "Himmel", "Erde/Land", "Feuer"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_e2", topicId: 34, prompt: "Was bedeutet die Wurzel 'aqua'?", options: ["Luft", "Wasser", "Erde", "Feuer"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_e3", topicId: 34, prompt: "Was bedeutet die Wurzel 'lum/luc'?", options: ["Dunkel", "Wasser", "Licht", "Kalt"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_e4", topicId: 34, prompt: "Was bedeutet die Wurzel 'mort'?", options: ["Leben", "Tod", "Liebe", "Kraft"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_e5", topicId: 34, prompt: "Was bedeutet die Vorsilbe 'mis-' in Wörtern wie 'misunderstand'?", options: ["wieder", "falsch/schlecht", "zu viel", "nicht genug"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_e6", topicId: 34, prompt: "Was bedeutet die Vorsilbe 'pre-' in Wörtern wie 'predict'?", options: ["nach", "gegen", "vor", "mit"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_e7", topicId: 34, prompt: "Was bedeutet die Nachsilbe '-ology'?", options: ["Furcht vor", "Lehre von/Wissenschaft", "Liebhaber von", "Fähigkeit zu"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_e8", topicId: 34, prompt: "Was bedeutet die Wurzel 'man/manu'?", options: ["Kopf", "Hand", "Fuß", "Arm"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_34_e9", topicId: 34, prompt: "Was bedeutet die Wurzel 'spec/spect'?", options: ["sprechen", "hören", "sehen/schauen", "denken"], correctIndex: 2),
        MathExamQuestion(id: "de_teach_34_e10", topicId: 34, prompt: "Was bedeutet die Nachsilbe '-phobia'?", options: ["Liebe zu", "Wissenschaft von", "Furcht/Angst vor", "Ähnlichkeit mit"], correctIndex: 2)
    ],
    35: [
        MathExamQuestion(id: "de_teach_35_e1", topicId: 35, prompt: "Welcher Satz verwendet ein Semikolon FALSCH?", options: ["I love English; it opens doors.", "She is tall; and she runs fast.", "He studied hard; he passed the test.", "I have three pets; a dog, a cat, and a fish."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e2", topicId: 35, prompt: "Welcher Satz zeigt FALSCHEN Parallelismus?", options: ["She likes reading, writing, and speaking.", "He enjoys to swim, hiking, and runs.", "They love singing, dancing, and acting.", "We prefer studying, practicing, and improving."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e3", topicId: 35, prompt: "Was ist ein 'misplaced modifier'?", options: ["Ein Modifier am Satzanfang", "Ein Modifier, der sich auf das falsche Wort bezieht", "Ein fehlender Modifier", "Ein doppelter Modifier"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e4", topicId: 35, prompt: "Welcher Satz hat einen 'dangling modifier'?", options: ["Running fast, she won the race.", "Running fast, the race was won.", "She won the race by running fast.", "While she ran fast, she won."], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e5", topicId: 35, prompt: "Wann verwendet man einen Doppelpunkt (:) vor einer Liste?", options: ["Immer vor einer Liste", "Wenn ein vollständiger Satz die Liste einleitet", "Nur nach Verben", "Nie vor einer Liste"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e6", topicId: 35, prompt: "Was ist ein 'run-on sentence'?", options: ["Ein sehr langer, aber korrekter Satz", "Zwei Hauptsätze ohne korrekte Verbindung", "Ein Satz ohne Subjekt", "Ein sehr kurzer Satz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e7", topicId: 35, prompt: "Wie behebt man einen 'comma splice'?", options: ["Komma entfernen", "FANBOYS-Konjunktion oder Semikolon hinzufügen", "Einen Bindestrich verwenden", "Nichts ändern"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e8", topicId: 35, prompt: "Was ist 'passive voice overuse'?", options: ["Zu viel Aktiv", "Übermäßige Verwendung des Passivs, macht Text schwerfällig", "Falsche Zeitform", "Zu viele Adjektive"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e9", topicId: 35, prompt: "Was ist ein 'sentence fragment'?", options: ["Ein vollständiger Satz", "Ein unvollständiger Satz ohne Subjekt oder Prädikat", "Ein langer Satz", "Ein Passivsatz"], correctIndex: 1),
        MathExamQuestion(id: "de_teach_35_e10", topicId: 35, prompt: "Welcher Satz ist grammatisch KORREKT?", options: ["Between you and I, this is hard.", "Between you and me, this is hard.", "Between you and myself, this is hard.", "Between I and you, this is hard."], correctIndex: 1)
    ]
]
